// <auto-generated />
using System;
using KCCMaterialFlow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KCCMaterialFlow.Infrastructure.Migrations
{
    [DbContext(typeof(KCCMaterialFlowDbContext))]
    [Migration("20260128055644_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KCCMaterialFlow.Module.BonEntree.Entities.Approbation", b =>
                {
                    b.Property<int>("IdApprobation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdApprobation");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdApprobation"));

                    b.Property<int>("BonId")
                        .HasColumnType("int")
                        .HasColumnName("BonId");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Commentaire");

                    b.Property<DateTime?>("DateAction")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateAction");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreation")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("EnAttente")
                        .HasColumnName("Decision");

                    b.Property<bool>("EstEtapeCourante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("EstEtapeCourante");

                    b.Property<string>("NomEtape")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NomEtape");

                    b.Property<int>("OrdreEtape")
                        .HasColumnType("int")
                        .HasColumnName("OrdreEtape");

                    b.Property<string>("ReservesEventuelles")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ReservesEventuelles");

                    b.Property<string>("StatutAttendu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("StatutAttendu");

                    b.Property<string>("UtilisateurFonction")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("UtilisateurFonction");

                    b.Property<string>("UtilisateurLogin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UtilisateurLogin");

                    b.Property<string>("UtilisateurNom")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UtilisateurNom");

                    b.HasKey("IdApprobation");

                    b.HasIndex("BonId")
                        .HasDatabaseName("IX_Approbations_Bon");

                    b.HasIndex("Decision")
                        .HasDatabaseName("IX_Approbations_Decision");

                    b.HasIndex("EstEtapeCourante")
                        .HasDatabaseName("IX_Approbations_EtapeCourante");

                    b.HasIndex("UtilisateurLogin")
                        .HasDatabaseName("IX_Approbations_Utilisateur");

                    b.HasIndex("BonId", "OrdreEtape")
                        .IsUnique()
                        .HasDatabaseName("IX_Approbations_Bon_Etape");

                    b.HasIndex("UtilisateurLogin", "Decision", "EstEtapeCourante")
                        .HasDatabaseName("IX_Approbations_Utilisateur_Decision_Courante");

                    b.ToTable("Approbations", "bem");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonEntree.Entities.Bon", b =>
                {
                    b.Property<int>("IdBon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdBon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBon"));

                    b.Property<string>("Commentaires")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Commentaires");

                    b.Property<string>("CreateurDepartement")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreateurDepartement");

                    b.Property<string>("CreateurLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreateurLogin");

                    b.Property<string>("CreateurNom")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CreateurNom");

                    b.Property<DateTime?>("DateAnnulation")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateAnnulation");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreation")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateExpiration");

                    b.Property<DateTime?>("DateGenerationQR")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateGenerationQR");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateModification");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Description");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Destination");

                    b.Property<bool>("EstAnnule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("EstAnnule");

                    b.Property<string>("ModificateurLogin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModificateurLogin");

                    b.Property<string>("MotifAnnulation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MotifAnnulation");

                    b.Property<string>("NumeroReference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NumeroReference");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Provenance");

                    b.Property<string>("QRCodeData")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("QRCodeData");

                    b.Property<string>("QRCodePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("QRCodePath");

                    b.Property<int>("Quantite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Quantite");

                    b.Property<string>("StatutActuel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("StatutActuel");

                    b.Property<string>("TypeBon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TypeBon");

                    b.Property<string>("TypeDiscriminator")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdBon");

                    b.HasIndex("CreateurLogin")
                        .HasDatabaseName("IX_Bons_Createur");

                    b.HasIndex("DateCreation")
                        .HasDatabaseName("IX_Bons_DateCreation");

                    b.HasIndex("NumeroReference")
                        .IsUnique()
                        .HasDatabaseName("IX_Bons_NumeroReference");

                    b.HasIndex("StatutActuel")
                        .HasDatabaseName("IX_Bons_Statut");

                    b.HasIndex("TypeBon")
                        .HasDatabaseName("IX_Bons_Type");

                    b.HasIndex("StatutActuel", "TypeBon", "DateCreation")
                        .HasDatabaseName("IX_Bons_Statut_Type_Date");

                    b.ToTable("Bons", "bem");

                    b.HasDiscriminator<string>("TypeDiscriminator").HasValue("Bon");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonEntree.Entities.BonEntreeHistory", b =>
                {
                    b.Property<int>("IdHistory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdHistory");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistory"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Action");

                    b.Property<string>("ActionBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ActionBy");

                    b.Property<string>("ActionByNom")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ActionByNom");

                    b.Property<DateTime>("ActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ActionDate")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ActionDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ActionDescription");

                    b.Property<string>("AdresseIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AdresseIP");

                    b.Property<int>("BonId")
                        .HasColumnType("int")
                        .HasColumnName("BonId");

                    b.Property<string>("ChangementsJson")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ChangementsJson");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Comment");

                    b.Property<string>("StatutApres")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("StatutApres");

                    b.Property<string>("StatutAvant")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("StatutAvant");

                    b.HasKey("IdHistory");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_BonEntreeHistory_Action");

                    b.HasIndex("ActionBy")
                        .HasDatabaseName("IX_BonEntreeHistory_ActionBy");

                    b.HasIndex("ActionDate")
                        .HasDatabaseName("IX_BonEntreeHistory_ActionDate");

                    b.HasIndex("BonId")
                        .HasDatabaseName("IX_BonEntreeHistory_Bon");

                    b.HasIndex("BonId", "ActionDate")
                        .HasDatabaseName("IX_BonEntreeHistory_Bon_Date");

                    b.ToTable("BonEntreeHistory", "bem");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonEntree.Entities.ItinerairePrevu", b =>
                {
                    b.Property<int>("IdItineraire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdItineraire");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItineraire"));

                    b.Property<string>("AgentLogin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("AgentLogin");

                    b.Property<string>("AgentNom")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("AgentNom");

                    b.Property<int>("BarriereId")
                        .HasColumnType("int")
                        .HasColumnName("BarriereId");

                    b.Property<string>("BarriereLocalisation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("BarriereLocalisation");

                    b.Property<string>("BarriereNom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("BarriereNom");

                    b.Property<int>("BonId")
                        .HasColumnType("int")
                        .HasColumnName("BonId");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreation")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DatePassage")
                        .HasColumnType("datetime2")
                        .HasColumnName("DatePassage");

                    b.Property<bool>("EstObligatoire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("EstObligatoire");

                    b.Property<string>("Observations")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Observations");

                    b.Property<int>("OrdrePassage")
                        .HasColumnType("int")
                        .HasColumnName("OrdrePassage");

                    b.Property<bool>("ScanEffectue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("ScanEffectue");

                    b.HasKey("IdItineraire");

                    b.HasIndex("BarriereId")
                        .HasDatabaseName("IX_ItinerairesPrevu_Barriere");

                    b.HasIndex("BonId")
                        .HasDatabaseName("IX_ItinerairesPrevu_Bon");

                    b.HasIndex("ScanEffectue")
                        .HasDatabaseName("IX_ItinerairesPrevu_Scan");

                    b.HasIndex("BonId", "OrdrePassage")
                        .IsUnique()
                        .HasDatabaseName("IX_ItinerairesPrevu_Bon_Ordre");

                    b.HasIndex("BonId", "ScanEffectue", "OrdrePassage")
                        .HasDatabaseName("IX_ItinerairesPrevu_Bon_Scan_Ordre");

                    b.ToTable("ItinerairesPrevu", "bem");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonEntree.Entities.Materiel", b =>
                {
                    b.Property<int>("IdMateriel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdMateriel");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMateriel"));

                    b.Property<int>("BonEntreeId")
                        .HasColumnType("int")
                        .HasColumnName("BonEntreeId");

                    b.Property<int?>("BonSortieId")
                        .HasColumnType("int")
                        .HasColumnName("BonSortieId");

                    b.Property<string>("CodeProduitSerial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CodeProduitSerial");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreation")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateModification");

                    b.Property<DateTime?>("DateSortie")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateSortie");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Designation");

                    b.Property<string>("Destination")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Destination");

                    b.Property<string>("Devise")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("USD")
                        .HasColumnName("Devise");

                    b.Property<bool>("EstRessorti")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("EstRessorti");

                    b.Property<string>("EtatEntree")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EtatEntree");

                    b.Property<string>("EtatSortie")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EtatSortie");

                    b.Property<string>("Marque")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Marque");

                    b.Property<string>("Modele")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Modele");

                    b.Property<string>("ObservationsEntree")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ObservationsEntree");

                    b.Property<string>("ObservationsSortie")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ObservationsSortie");

                    b.Property<string>("PhotoEntree")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PhotoEntree");

                    b.Property<string>("PhotoSortie")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PhotoSortie");

                    b.Property<string>("Provenance")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Provenance");

                    b.Property<int>("Quantite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("Quantite");

                    b.Property<string>("TypeMateriel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Autre")
                        .HasColumnName("TypeMateriel");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pcs")
                        .HasColumnName("Unite");

                    b.Property<decimal?>("ValeurEstimee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValeurEstimee");

                    b.HasKey("IdMateriel");

                    b.HasIndex("BonEntreeId")
                        .HasDatabaseName("IX_Materiels_BonEntree");

                    b.HasIndex("BonSortieId")
                        .HasDatabaseName("IX_Materiels_BonSortie");

                    b.HasIndex("CodeProduitSerial")
                        .HasDatabaseName("IX_Materiels_CodeSerial");

                    b.HasIndex("EstRessorti")
                        .HasDatabaseName("IX_Materiels_Ressorti");

                    b.HasIndex("TypeMateriel")
                        .HasDatabaseName("IX_Materiels_Type");

                    b.HasIndex("BonEntreeId", "EstRessorti")
                        .HasDatabaseName("IX_Materiels_BonEntree_Ressorti");

                    b.ToTable("Materiels", "bem");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.Shared.Entities.Barriere", b =>
                {
                    b.Property<int>("IdBarriere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdBarriere");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBarriere"));

                    b.Property<string>("CodeBarriere")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CodeBarriere");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreation")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateModification");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<bool>("EstActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("EstActive");

                    b.Property<string>("HorairesOuverture")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HorairesOuverture");

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Localisation");

                    b.Property<string>("NomBarriere")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NomBarriere");

                    b.Property<string>("Telephone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Telephone");

                    b.Property<string>("TypeBarriere")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Mixte")
                        .HasColumnName("TypeBarriere");

                    b.HasKey("IdBarriere");

                    b.HasIndex("CodeBarriere")
                        .IsUnique()
                        .HasDatabaseName("IX_Barrieres_Code");

                    b.HasIndex("EstActive")
                        .HasDatabaseName("IX_Barrieres_EstActive");

                    b.HasIndex("Localisation")
                        .HasDatabaseName("IX_Barrieres_Localisation");

                    b.HasIndex("TypeBarriere")
                        .HasDatabaseName("IX_Barrieres_Type");

                    b.ToTable("Barrieres", "shared");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.Shared.Entities.Departement", b =>
                {
                    b.Property<int>("IdDepartement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDepartement");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartement"));

                    b.Property<string>("CodeDepartement")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CodeDepartement");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreation")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateModification");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<bool>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("EstActif");

                    b.Property<string>("NomDepartement")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NomDepartement");

                    b.Property<string>("ResponsableEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ResponsableEmail");

                    b.Property<string>("ResponsableLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ResponsableLogin");

                    b.Property<string>("ResponsableNom")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ResponsableNom");

                    b.HasKey("IdDepartement");

                    b.HasIndex("CodeDepartement")
                        .IsUnique()
                        .HasDatabaseName("IX_Departements_Code");

                    b.HasIndex("EstActif")
                        .HasDatabaseName("IX_Departements_EstActif");

                    b.HasIndex("ResponsableLogin")
                        .HasDatabaseName("IX_Departements_Responsable");

                    b.ToTable("Departements", "shared");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.Shared.Entities.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdUtilisateur");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreation")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateModification");

                    b.Property<string>("Departement")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Departement");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("datetime2")
                        .HasColumnName("DerniereConnexion");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Email");

                    b.Property<bool>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("EstActif");

                    b.Property<string>("Fonction")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Fonction");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Login");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NomComplet");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Utilisateur")
                        .HasColumnName("Role");

                    b.Property<string>("Telephone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Telephone");

                    b.HasKey("IdUtilisateur");

                    b.HasIndex("Departement")
                        .HasDatabaseName("IX_Utilisateurs_Departement");

                    b.HasIndex("EstActif")
                        .HasDatabaseName("IX_Utilisateurs_EstActif");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("IX_Utilisateurs_Login");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_Utilisateurs_Role");

                    b.ToTable("Utilisateurs", "shared");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonEntree.Entities.BonEntree", b =>
                {
                    b.HasBaseType("KCCMaterialFlow.Module.BonEntree.Entities.Bon");

                    b.Property<string>("AgentEntreeLogin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("AgentEntreeLogin");

                    b.Property<int?>("BarriereEntreeId")
                        .HasColumnType("int")
                        .HasColumnName("BarriereEntreeId");

                    b.Property<string>("BarriereEntreeNom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("BarriereEntreeNom");

                    b.Property<int?>("BonSortieLieId")
                        .HasColumnType("int")
                        .HasColumnName("BonSortieLieId");

                    b.Property<DateTime?>("DateEntreeEffective")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateEntreeEffective");

                    b.Property<DateTime?>("DateEntreePrevue")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateEntreePrevue");

                    b.Property<DateTime?>("DateToutRessorti")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateToutRessorti");

                    b.Property<bool>("DoitRessortir")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("DoitRessortir");

                    b.Property<string>("EmailContractant")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EmailContractant");

                    b.Property<string>("EscorteurLogin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EscorteurLogin");

                    b.Property<string>("FonctionEscorteur")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("FonctionEscorteur");

                    b.Property<string>("HostDepartment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HostDepartment");

                    b.Property<string>("NomCompagnie")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NomCompagnie");

                    b.Property<string>("NomEscorteur")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NomEscorteur");

                    b.Property<string>("NumeroContrat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NumeroContrat");

                    b.Property<string>("ObservationsEntree")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ObservationsEntree");

                    b.Property<string>("ReasonOnSite")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ReasonOnSite");

                    b.Property<string>("SiteManager")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SiteManager");

                    b.Property<string>("SiteManagerLogin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SiteManagerLogin");

                    b.Property<string>("TelephoneContractant")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TelephoneContractant");

                    b.Property<bool>("ToutRessorti")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("ToutRessorti");

                    b.Property<string>("ZoneTravail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ZoneTravail");

                    b.HasIndex("BonSortieLieId")
                        .HasDatabaseName("IX_Bons_BonSortieLie");

                    b.HasIndex("HostDepartment")
                        .HasDatabaseName("IX_Bons_HostDepartment");

                    b.HasIndex("NomCompagnie")
                        .HasDatabaseName("IX_Bons_NomCompagnie");

                    b.HasIndex("SiteManagerLogin")
                        .HasDatabaseName("IX_Bons_SiteManager");

                    b.HasIndex("DoitRessortir", "ToutRessorti")
                        .HasDatabaseName("IX_Bons_Ressortie");

                    b.ToTable("Bons", "bem");

                    b.HasDiscriminator().HasValue("BonEntree");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonEntree.Entities.Approbation", b =>
                {
                    b.HasOne("KCCMaterialFlow.Module.BonEntree.Entities.Bon", "Bon")
                        .WithMany()
                        .HasForeignKey("BonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bon");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonEntree.Entities.BonEntreeHistory", b =>
                {
                    b.HasOne("KCCMaterialFlow.Module.BonEntree.Entities.Bon", "Bon")
                        .WithMany()
                        .HasForeignKey("BonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bon");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonEntree.Entities.ItinerairePrevu", b =>
                {
                    b.HasOne("KCCMaterialFlow.Module.BonEntree.Entities.Bon", "Bon")
                        .WithMany()
                        .HasForeignKey("BonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bon");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonEntree.Entities.Materiel", b =>
                {
                    b.HasOne("KCCMaterialFlow.Module.BonEntree.Entities.BonEntree", "BonEntree")
                        .WithMany("Materiels")
                        .HasForeignKey("BonEntreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonEntree");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonEntree.Entities.BonEntree", b =>
                {
                    b.Navigation("Materiels");
                });
#pragma warning restore 612, 618
        }
    }
}
