// <auto-generated />
using System;
using KCCMaterialFlow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KCCMaterialFlow.Infrastructure.Migrations
{
    [DbContext(typeof(KCCMaterialFlowDbContext))]
    [Migration("20260129125918_AddBonSortieModule")]
    partial class AddBonSortieModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KCCMaterialFlow.Module.BonEntree.Entities.Approbation", b =>
                {
                    b.Property<int>("IdApprobation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdApprobation");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdApprobation"));

                    b.Property<int>("BonId")
                        .HasColumnType("int")
                        .HasColumnName("BonId");

                    b.Property<DateTime?>("DateAction")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateAction");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("En attente")
                        .HasColumnName("Decision");

                    b.Property<int>("OrdreEtape")
                        .HasColumnType("int")
                        .HasColumnName("OrdreEtape");

                    b.Property<string>("ReservesEventuelles")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ReservesEventuelles");

                    b.HasKey("IdApprobation");

                    b.HasIndex("BonId")
                        .HasDatabaseName("IX_Approbations_Bon");

                    b.HasIndex("Decision")
                        .HasDatabaseName("IX_Approbations_Decision");

                    b.HasIndex("BonId", "OrdreEtape")
                        .IsUnique()
                        .HasDatabaseName("IX_Approbations_Bon_Etape");

                    b.ToTable("Approbations", "bem");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonEntree.Entities.Bon", b =>
                {
                    b.Property<int>("IdBon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdBon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBon"));

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreation")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateExpiration");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Description");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Destination");

                    b.Property<string>("NumeroReference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NumeroReference");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Provenance");

                    b.Property<int>("Quantite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Quantite");

                    b.Property<string>("StatutActuel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("StatutActuel");

                    b.Property<string>("TypeDiscriminator")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdBon");

                    b.HasIndex("DateCreation")
                        .HasDatabaseName("IX_Bons_DateCreation");

                    b.HasIndex("NumeroReference")
                        .IsUnique()
                        .HasDatabaseName("IX_Bons_NumeroReference");

                    b.HasIndex("StatutActuel")
                        .HasDatabaseName("IX_Bons_Statut");

                    b.ToTable("Bons", "bem");

                    b.HasDiscriminator<string>("TypeDiscriminator").HasValue("Bon");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonEntree.Entities.BonEntreeHistory", b =>
                {
                    b.Property<int>("IdHistory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdHistory");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistory"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Action");

                    b.Property<string>("ActionBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ActionBy");

                    b.Property<string>("ActionByNom")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ActionByNom");

                    b.Property<DateTime>("ActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ActionDate")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ActionDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ActionDescription");

                    b.Property<string>("AdresseIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AdresseIP");

                    b.Property<int>("BonId")
                        .HasColumnType("int")
                        .HasColumnName("BonId");

                    b.Property<string>("ChangementsJson")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ChangementsJson");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Comment");

                    b.Property<string>("StatutApres")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("StatutApres");

                    b.Property<string>("StatutAvant")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("StatutAvant");

                    b.HasKey("IdHistory");

                    b.HasIndex("Action")
                        .HasDatabaseName("IX_BonEntreeHistory_Action");

                    b.HasIndex("ActionBy")
                        .HasDatabaseName("IX_BonEntreeHistory_ActionBy");

                    b.HasIndex("ActionDate")
                        .HasDatabaseName("IX_BonEntreeHistory_ActionDate");

                    b.HasIndex("BonId")
                        .HasDatabaseName("IX_BonEntreeHistory_Bon");

                    b.HasIndex("BonId", "ActionDate")
                        .HasDatabaseName("IX_BonEntreeHistory_Bon_Date");

                    b.ToTable("BonEntreeHistory", "bem");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonEntree.Entities.ItinerairePrevu", b =>
                {
                    b.Property<int>("IdItineraire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdItineraire");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItineraire"));

                    b.Property<int>("BarriereId")
                        .HasColumnType("int")
                        .HasColumnName("BarriereId");

                    b.Property<int>("BonId")
                        .HasColumnType("int")
                        .HasColumnName("BonId");

                    b.Property<int>("OrdrePassage")
                        .HasColumnType("int")
                        .HasColumnName("OrdrePassage");

                    b.HasKey("IdItineraire");

                    b.HasIndex("BarriereId")
                        .HasDatabaseName("IX_ItinerairesPrevu_Barriere");

                    b.HasIndex("BonId")
                        .HasDatabaseName("IX_ItinerairesPrevu_Bon");

                    b.HasIndex("BonId", "OrdrePassage")
                        .IsUnique()
                        .HasDatabaseName("IX_ItinerairesPrevu_Bon_Ordre");

                    b.ToTable("ItinerairesPrevu", "bem");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonEntree.Entities.Materiel", b =>
                {
                    b.Property<int>("IdMateriel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdMateriel");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMateriel"));

                    b.Property<int>("BonId")
                        .HasColumnType("int")
                        .HasColumnName("BonId");

                    b.Property<string>("CodeProduitSerial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CodeProduitSerial");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Designation");

                    b.Property<string>("Destination")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Destination");

                    b.Property<string>("Provenance")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Provenance");

                    b.Property<decimal>("Quantite")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(1m)
                        .HasColumnName("Quantite");

                    b.HasKey("IdMateriel");

                    b.HasIndex("BonId")
                        .HasDatabaseName("IX_Materiels_Bon");

                    b.HasIndex("CodeProduitSerial")
                        .HasDatabaseName("IX_Materiels_CodeSerial");

                    b.ToTable("Materiels", "bem");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonSortie.Entities.ApprobationSortie", b =>
                {
                    b.Property<int>("IdApprobation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdApprobation");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdApprobation"));

                    b.Property<string>("ApprobateurLogin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ApprobateurLogin");

                    b.Property<string>("ApprobateurNom")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ApprobateurNom");

                    b.Property<int>("BonSortieId")
                        .HasColumnType("int")
                        .HasColumnName("BonSortieId");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Commentaire");

                    b.Property<DateTime?>("DateAction")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateAction");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("En attente")
                        .HasColumnName("Decision");

                    b.Property<string>("NomEtape")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NomEtape");

                    b.Property<int>("OrdreEtape")
                        .HasColumnType("int")
                        .HasColumnName("OrdreEtape");

                    b.HasKey("IdApprobation");

                    b.HasIndex("BonSortieId")
                        .HasDatabaseName("IX_ApprobationsSortie_BonSortieId");

                    b.HasIndex("BonSortieId", "OrdreEtape")
                        .HasDatabaseName("IX_ApprobationsSortie_Etape");

                    b.ToTable("ApprobationsSortie", "bsm");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonSortie.Entities.BonSortie", b =>
                {
                    b.Property<int>("IdBon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdBon");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBon"));

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreation")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateExpiration");

                    b.Property<string>("DepartementDemandeur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DepartementDemandeur");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Description");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Destination");

                    b.Property<bool>("EstDefinitif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("EstDefinitif");

                    b.Property<string>("FonctionDemandeur")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("FonctionDemandeur");

                    b.Property<string>("MotifSortie")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("MotifSortie");

                    b.Property<string>("NomDemandeur")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NomDemandeur");

                    b.Property<string>("NumeroReference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NumeroReference");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Provenance");

                    b.Property<int>("Quantite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Quantite");

                    b.Property<string>("StatutActuel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("StatutActuel");

                    b.Property<string>("TypeSortie")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdBon");

                    b.HasIndex("DateCreation")
                        .HasDatabaseName("IX_BonsSortie_DateCreation");

                    b.HasIndex("DepartementDemandeur")
                        .HasDatabaseName("IX_BonsSortie_Departement");

                    b.HasIndex("NumeroReference")
                        .IsUnique()
                        .HasDatabaseName("IX_BonsSortie_NumeroReference");

                    b.HasIndex("StatutActuel")
                        .HasDatabaseName("IX_BonsSortie_Statut");

                    b.ToTable("BonsSortie", "bsm");

                    b.HasDiscriminator<string>("TypeSortie").HasValue("BonSortie");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonSortie.Entities.BonSortieHistory", b =>
                {
                    b.Property<int>("IdHistory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdHistory");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistory"));

                    b.Property<string>("AdresseIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AdresseIP");

                    b.Property<int>("BonSortieId")
                        .HasColumnType("int")
                        .HasColumnName("BonSortieId");

                    b.Property<DateTime>("DateAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateAction")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Description");

                    b.Property<string>("StatutApres")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("StatutApres");

                    b.Property<string>("StatutAvant")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("StatutAvant");

                    b.Property<string>("TypeAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TypeAction");

                    b.Property<string>("UtilisateurLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UtilisateurLogin");

                    b.Property<string>("UtilisateurNom")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UtilisateurNom");

                    b.HasKey("IdHistory");

                    b.HasIndex("BonSortieId")
                        .HasDatabaseName("IX_BonSortieHistories_BonSortieId");

                    b.HasIndex("DateAction")
                        .HasDatabaseName("IX_BonSortieHistories_DateAction");

                    b.HasIndex("UtilisateurLogin")
                        .HasDatabaseName("IX_BonSortieHistories_Utilisateur");

                    b.ToTable("BonSortieHistories", "bsm");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonSortie.Entities.ItineraireSortie", b =>
                {
                    b.Property<int>("IdItineraire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdItineraire");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItineraire"));

                    b.Property<int>("BarriereId")
                        .HasColumnType("int")
                        .HasColumnName("BarriereId");

                    b.Property<int>("BonSortieId")
                        .HasColumnType("int")
                        .HasColumnName("BonSortieId");

                    b.Property<DateTime?>("DatePassageEffective")
                        .HasColumnType("datetime2")
                        .HasColumnName("DatePassageEffective");

                    b.Property<DateTime?>("DatePassagePrevue")
                        .HasColumnType("datetime2")
                        .HasColumnName("DatePassagePrevue");

                    b.Property<string>("Observations")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Observations");

                    b.Property<int>("OrdrePassage")
                        .HasColumnType("int")
                        .HasColumnName("OrdrePassage");

                    b.Property<string>("StatutPassage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Prévu")
                        .HasColumnName("StatutPassage");

                    b.HasKey("IdItineraire");

                    b.HasIndex("BarriereId")
                        .HasDatabaseName("IX_ItinerairesSortie_BarriereId");

                    b.HasIndex("BonSortieId")
                        .HasDatabaseName("IX_ItinerairesSortie_BonSortieId");

                    b.HasIndex("BonSortieId", "OrdrePassage")
                        .HasDatabaseName("IX_ItinerairesSortie_Ordre");

                    b.ToTable("ItinerairesSortie", "bsm");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonSortie.Entities.MaterielSortie", b =>
                {
                    b.Property<int>("IdMateriel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdMateriel");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMateriel"));

                    b.Property<int>("BonSortieId")
                        .HasColumnType("int")
                        .HasColumnName("BonSortieId");

                    b.Property<string>("CodeProduitSerial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CodeProduitSerial");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Designation");

                    b.Property<string>("Destination")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Destination");

                    b.Property<string>("Provenance")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Provenance");

                    b.Property<decimal>("Quantite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(1m)
                        .HasColumnName("Quantite");

                    b.HasKey("IdMateriel");

                    b.HasIndex("BonSortieId")
                        .HasDatabaseName("IX_MaterielsSortie_BonSortieId");

                    b.HasIndex("CodeProduitSerial")
                        .HasDatabaseName("IX_MaterielsSortie_CodeProduit");

                    b.ToTable("MaterielsSortie", "bsm");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.Shared.Entities.Barriere", b =>
                {
                    b.Property<int>("IdBarriere")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdBarriere");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBarriere"));

                    b.Property<string>("CodeBarriere")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CodeBarriere");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreation")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateModification");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<bool>("EstActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("EstActive");

                    b.Property<string>("HorairesOuverture")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HorairesOuverture");

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Localisation");

                    b.Property<string>("NomBarriere")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NomBarriere");

                    b.Property<string>("Telephone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Telephone");

                    b.Property<string>("TypeBarriere")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Mixte")
                        .HasColumnName("TypeBarriere");

                    b.HasKey("IdBarriere");

                    b.HasIndex("CodeBarriere")
                        .IsUnique()
                        .HasDatabaseName("IX_Barrieres_Code");

                    b.HasIndex("EstActive")
                        .HasDatabaseName("IX_Barrieres_EstActive");

                    b.HasIndex("Localisation")
                        .HasDatabaseName("IX_Barrieres_Localisation");

                    b.HasIndex("TypeBarriere")
                        .HasDatabaseName("IX_Barrieres_Type");

                    b.ToTable("Barrieres", "shared");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.Shared.Entities.Departement", b =>
                {
                    b.Property<int>("IdDepartement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDepartement");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartement"));

                    b.Property<string>("CodeDepartement")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CodeDepartement");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreation")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateModification");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<bool>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("EstActif");

                    b.Property<string>("NomDepartement")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NomDepartement");

                    b.Property<string>("ResponsableEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ResponsableEmail");

                    b.Property<string>("ResponsableLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ResponsableLogin");

                    b.Property<string>("ResponsableNom")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ResponsableNom");

                    b.HasKey("IdDepartement");

                    b.HasIndex("CodeDepartement")
                        .IsUnique()
                        .HasDatabaseName("IX_Departements_Code");

                    b.HasIndex("EstActif")
                        .HasDatabaseName("IX_Departements_EstActif");

                    b.HasIndex("ResponsableLogin")
                        .HasDatabaseName("IX_Departements_Responsable");

                    b.ToTable("Departements", "shared");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.Shared.Entities.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdUtilisateur");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("DateCreation")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateModification");

                    b.Property<string>("Departement")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Departement");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("datetime2")
                        .HasColumnName("DerniereConnexion");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Email");

                    b.Property<bool>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("EstActif");

                    b.Property<string>("Fonction")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Fonction");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Login");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NomComplet");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Utilisateur")
                        .HasColumnName("Role");

                    b.Property<string>("Telephone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Telephone");

                    b.HasKey("IdUtilisateur");

                    b.HasIndex("Departement")
                        .HasDatabaseName("IX_Utilisateurs_Departement");

                    b.HasIndex("EstActif")
                        .HasDatabaseName("IX_Utilisateurs_EstActif");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("IX_Utilisateurs_Login");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_Utilisateurs_Role");

                    b.ToTable("Utilisateurs", "shared");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonEntree.Entities.BonEntree", b =>
                {
                    b.HasBaseType("KCCMaterialFlow.Module.BonEntree.Entities.Bon");

                    b.Property<string>("EmailContractant")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EmailContractant");

                    b.Property<string>("FonctionEscorteur")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("FonctionEscorteur");

                    b.Property<string>("HostDepartment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HostDepartment");

                    b.Property<string>("NomCompagnie")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NomCompagnie");

                    b.Property<string>("NomEscorteur")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NomEscorteur");

                    b.Property<string>("NumeroContrat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NumeroContrat");

                    b.Property<string>("ReasonOnSite")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ReasonOnSite");

                    b.Property<string>("SiteManager")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SiteManager");

                    b.HasIndex("HostDepartment")
                        .HasDatabaseName("IX_Bons_HostDepartment");

                    b.HasIndex("NomCompagnie")
                        .HasDatabaseName("IX_Bons_NomCompagnie");

                    b.ToTable("Bons", "bem");

                    b.HasDiscriminator().HasValue("BonEntree");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonSortie.Entities.BonSortieExterne", b =>
                {
                    b.HasBaseType("KCCMaterialFlow.Module.BonSortie.Entities.BonSortie");

                    b.Property<string>("AdresseDestination")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AdresseDestination");

                    b.Property<int?>("BonEntreeAssocieId")
                        .HasColumnType("int")
                        .HasColumnName("BonEntreeAssocieId");

                    b.Property<string>("NomChauffeur")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NomChauffeur");

                    b.Property<string>("NomDestinataire")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NomDestinataire");

                    b.Property<string>("NumeroVehicule")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NumeroVehicule");

                    b.Property<string>("TelephoneChauffeur")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TelephoneChauffeur");

                    b.Property<string>("TypeMateriel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TypeMateriel");

                    b.HasIndex("BonEntreeAssocieId")
                        .HasDatabaseName("IX_BonsSortie_BonEntreeAssocie");

                    b.HasIndex("NomDestinataire")
                        .HasDatabaseName("IX_BonsSortie_Destinataire");

                    b.HasIndex("TypeMateriel")
                        .HasDatabaseName("IX_BonsSortie_TypeMateriel");

                    b.ToTable("BonsSortie", "bsm");

                    b.HasDiscriminator().HasValue("Externe");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonSortie.Entities.BonSortieInterne", b =>
                {
                    b.HasBaseType("KCCMaterialFlow.Module.BonSortie.Entities.BonSortie");

                    b.Property<DateTime?>("DateTransfertEffective")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateTransfertEffective");

                    b.Property<DateTime?>("DateTransfertPrevue")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateTransfertPrevue");

                    b.Property<string>("DepartementDestination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DepartementDestination");

                    b.Property<string>("DepartementOrigine")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DepartementOrigine");

                    b.Property<string>("EmailReceveur")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EmailReceveur");

                    b.Property<string>("FonctionReceveur")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("FonctionReceveur");

                    b.Property<string>("LocalisationDestination")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LocalisationDestination");

                    b.Property<string>("NomReceveur")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NomReceveur");

                    b.Property<string>("TypeMateriel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TypeMaterielInterne");

                    b.HasIndex("DepartementDestination")
                        .HasDatabaseName("IX_BonsSortie_DeptDestination");

                    b.HasIndex("DepartementOrigine")
                        .HasDatabaseName("IX_BonsSortie_DeptOrigine");

                    b.HasIndex("DepartementOrigine", "DepartementDestination")
                        .HasDatabaseName("IX_BonsSortie_Transfert");

                    b.ToTable("BonsSortie", "bsm");

                    b.HasDiscriminator().HasValue("Interne");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonSortie.Entities.Pret", b =>
                {
                    b.HasBaseType("KCCMaterialFlow.Module.BonSortie.Entities.BonSortieExterne");

                    b.Property<DateTime?>("DateRetourEffective")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateRetourEffective");

                    b.Property<DateTime>("DateRetourPrevue")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateRetourPrevue");

                    b.Property<bool>("EstRetourne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("EstRetourne");

                    b.Property<string>("EtatRetour")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("EtatRetour");

                    b.Property<string>("ReceptionnePar")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ReceptionnePar");

                    b.HasIndex("DateRetourPrevue")
                        .HasDatabaseName("IX_BonsSortie_DateRetourPrevue");

                    b.HasIndex("EstRetourne")
                        .HasDatabaseName("IX_BonsSortie_EstRetourne");

                    b.HasIndex("EstRetourne", "DateRetourPrevue")
                        .HasDatabaseName("IX_BonsSortie_PretsEnRetard");

                    b.ToTable("BonsSortie", "bsm");

                    b.HasDiscriminator().HasValue("Pret");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonEntree.Entities.Approbation", b =>
                {
                    b.HasOne("KCCMaterialFlow.Module.BonEntree.Entities.Bon", "Bon")
                        .WithMany("Approbations")
                        .HasForeignKey("BonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bon");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonEntree.Entities.BonEntreeHistory", b =>
                {
                    b.HasOne("KCCMaterialFlow.Module.BonEntree.Entities.Bon", "Bon")
                        .WithMany()
                        .HasForeignKey("BonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bon");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonEntree.Entities.ItinerairePrevu", b =>
                {
                    b.HasOne("KCCMaterialFlow.Module.BonEntree.Entities.Bon", "Bon")
                        .WithMany("ItinerairesPrevu")
                        .HasForeignKey("BonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bon");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonEntree.Entities.Materiel", b =>
                {
                    b.HasOne("KCCMaterialFlow.Module.BonEntree.Entities.Bon", "Bon")
                        .WithMany("Materiels")
                        .HasForeignKey("BonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bon");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonSortie.Entities.ApprobationSortie", b =>
                {
                    b.HasOne("KCCMaterialFlow.Module.BonSortie.Entities.BonSortie", "BonSortie")
                        .WithMany("Approbations")
                        .HasForeignKey("BonSortieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonSortie");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonSortie.Entities.BonSortieHistory", b =>
                {
                    b.HasOne("KCCMaterialFlow.Module.BonSortie.Entities.BonSortie", "BonSortie")
                        .WithMany("Historiques")
                        .HasForeignKey("BonSortieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonSortie");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonSortie.Entities.ItineraireSortie", b =>
                {
                    b.HasOne("KCCMaterialFlow.Module.BonSortie.Entities.BonSortie", "BonSortie")
                        .WithMany("Itineraires")
                        .HasForeignKey("BonSortieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonSortie");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonSortie.Entities.MaterielSortie", b =>
                {
                    b.HasOne("KCCMaterialFlow.Module.BonSortie.Entities.BonSortie", "BonSortie")
                        .WithMany("Materiels")
                        .HasForeignKey("BonSortieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonSortie");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonSortie.Entities.BonSortieExterne", b =>
                {
                    b.HasOne("KCCMaterialFlow.Module.BonEntree.Entities.BonEntree", "BonEntreeAssocie")
                        .WithMany()
                        .HasForeignKey("BonEntreeAssocieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BonEntreeAssocie");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonEntree.Entities.Bon", b =>
                {
                    b.Navigation("Approbations");

                    b.Navigation("ItinerairesPrevu");

                    b.Navigation("Materiels");
                });

            modelBuilder.Entity("KCCMaterialFlow.Module.BonSortie.Entities.BonSortie", b =>
                {
                    b.Navigation("Approbations");

                    b.Navigation("Historiques");

                    b.Navigation("Itineraires");

                    b.Navigation("Materiels");
                });
#pragma warning restore 612, 618
        }
    }
}
