// Script to translate English values in SharedResource.fr.resx to French
// Uses simple line-by-line replacement by key name

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Xml;
using System.Xml.Linq;

var file = @"c:\Users\ikasa\source\repos\Materiels\src\KCCMaterialFlow.Host\Resources\SharedResource.fr.resx";

// Dictionary: key name -> French value
var translations = new Dictionary<string, string>
{
    // Buttons
    ["Btn_Add"] = "Ajouter",
    ["Btn_Confirm"] = "Confirmer",
    ["Btn_Search"] = "Rechercher",
    ["Btn_Filter"] = "Filtrer",
    ["Filter_DateFrom"] = "De",
    ["Filter_DateTo"] = "Ã€",
    ["Btn_Clear"] = "Effacer",
    ["Btn_Stop"] = "ArrÃªter",
    ["Btn_Delete"] = "Supprimer",
    ["Btn_Save"] = "Enregistrer",
    ["Btn_View"] = "Voir",
    ["Btn_Import"] = "Importer",
    ["Btn_Download"] = "TÃ©lÃ©charger",
    ["Btn_Activate"] = "Activer",
    ["Btn_Deactivate"] = "DÃ©sactiver",
    ["Btn_Yes"] = "Oui",
    ["Btn_No"] = "Non",
    ["Btn_NewBEM"] = "Nouveau bon d'entrÃ©e",
    ["Btn_NewBSM"] = "Nouveau bon de sortie",
    ["Btn_AddMaterial"] = "Ajouter un matÃ©riel",
    ["Btn_Detail"] = "DÃ©tail",

    // Labels
    ["Lbl_Error"] = "Erreur",
    ["Lbl_NoData"] = "Aucune donnÃ©e",
    ["Lbl_Name"] = "Nom",
    ["Lbl_Employee"] = "EmployÃ©",
    ["Lbl_Reference"] = "RÃ©fÃ©rence",
    ["Lbl_Quantity"] = "QuantitÃ©",
    ["Lbl_Comments"] = "Commentaires",
    ["Lbl_CreatedAt"] = "CrÃ©Ã© le",
    ["Lbl_CreatedBy"] = "CrÃ©Ã© par",
    ["Lbl_UpdatedAt"] = "Mis Ã  jour le",
    ["Lbl_Requester"] = "Demandeur",
    ["Lbl_Approver"] = "Approbateur",
    ["Lbl_Department"] = "DÃ©partement",
    ["Lbl_Matricule"] = "Matricule",
    ["Lbl_Reason"] = "Motif",
    ["Lbl_Order"] = "Ordre",
    ["Lbl_Contract"] = "Contrat",
    ["Lbl_Company"] = "SociÃ©tÃ©",
    ["Lbl_Material"] = "MatÃ©riel",
    ["Lbl_Requester_short"] = "Dem.",
    ["Lbl_EntryDate"] = "Date d'entrÃ©e",
    ["Lbl_ExitDate"] = "Date de sortie",
    ["Lbl_SubmittedAt"] = "Soumis le",
    ["Lbl_ApprovedAt"] = "ApprouvÃ© le",
    ["Lbl_RejectedAt"] = "RejetÃ© le",
    ["Lbl_Filters"] = "Filtres",
    ["Lbl_Results"] = "RÃ©sultats",
    ["Lbl_SelectAll"] = "Tout sÃ©lectionner",
    ["Lbl_Profile"] = "Profil",
    ["Lbl_Permissions"] = "Autorisations",
    ["Lbl_Search"] = "Rechercher",
    ["Lbl_Status"] = "Statut",
    ["Lbl_All"] = "Tous",
    ["Lbl_None"] = "Aucun",
    ["Lbl_Inactive"] = "Inactif",
    ["Lbl_NoData"] = "Aucune donnÃ©e trouvÃ©e.",
    ["Lbl_Required"] = "obligatoire",
    ["Lbl_Optional"] = "optionnel",
    ["Lbl_At"] = "Ã ",
    ["Lbl_By"] = "par",
    ["Lbl_From"] = "De",
    ["Lbl_To"] = "Ã€",
    ["Lbl_Comment"] = "Commentaire",
    ["Lbl_Step"] = "Ã‰tape",
    ["Lbl_Filter"] = "Filtre",
    ["Lbl_ActiveFilter"] = "Filtre actif :",
    ["Lbl_Draft"] = "Brouillon",
    ["Lbl_Pending"] = "En attente",
    ["Lbl_Approved"] = "ApprouvÃ©",
    ["Lbl_Rejected"] = "RejetÃ©",
    ["Lbl_Returned"] = "RetournÃ©",
    ["Lbl_Completed"] = "ComplÃ©tÃ©",
    ["Lbl_Cancelled"] = "AnnulÃ©",

    // Statuts
    ["Status_Draft"] = "Brouillon",
    ["Status_Submitted"] = "Soumis",
    ["Status_Approved"] = "ApprouvÃ©",
    ["Status_Rejected"] = "RejetÃ©",
    ["Status_Returned"] = "RetournÃ©",
    ["Status_Cancelled"] = "AnnulÃ©",
    ["Status_Pending"] = "En attente",
    ["Status_Completed"] = "ComplÃ©tÃ©",
    ["Status_InProgress"] = "En cours",
    ["Statut_Draft"] = "Brouillon",
    ["Statut_Approved"] = "ApprouvÃ©",
    ["Statut_Rejected"] = "RejetÃ©",
    ["Statut_Returned"] = "RetournÃ©",
    ["Statut_Cancelled"] = "AnnulÃ©",
    ["Statut_PendingIT"] = "En attente IT",
    ["Statut_PendingEnv"] = "En attente ENV",
    ["Statut_PendingId"] = "En attente ID",

    // Workflow
    ["Wf_ApprovalWorkflow"] = "Flux d'approbation",
    ["Wf_Pending"] = "En attente",
    ["Wf_WaitingFor"] = "En attente de",
    ["Wf_OneOf"] = "l'un de :",
    ["Wf_ApprovedBy"] = "ApprouvÃ© par",
    ["Wf_RejectedBy"] = "RejetÃ© par",
    ["Wf_ReturnedBy"] = "RetournÃ© par",
    ["Wf_SpecialApprovers"] = "Approbateurs spÃ©ciaux",
    ["Wf_NoApproverConfigured"] = "Aucun approbateur configurÃ©",
    ["Wf_Step"] = "Ã‰tape",
    ["Wf_Decision"] = "DÃ©cision",
    ["Wf_DecisionDate"] = "Date de dÃ©cision",
    ["Wf_BSM"] = "BSM â€” Bon de sortie matÃ©riel",
    ["Wf_BEM"] = "BEM â€” Bon d'entrÃ©e matÃ©riel",
    ["Wf_Updated"] = "Flux d'approbation mis Ã  jour avec succÃ¨s.",

    // BEM
    ["Bem_Title"] = "Bon d'entrÃ©e matÃ©riel",
    ["Bem_New"] = "Nouveau bon d'entrÃ©e",
    ["Bem_List"] = "Bons d'entrÃ©e",
    ["Bem_EntryDate"] = "Date d'entrÃ©e",
    ["Bem_ReasonEntry"] = "Motif d'entrÃ©e",
    ["Bem_MaterialsList"] = "Liste des matÃ©riels",

    // BSM
    ["Bsm_Title"] = "Bon de sortie matÃ©riel",
    ["Bsm_New"] = "Nouveau bon de sortie",
    ["Bsm_List"] = "Bons de sortie",
    ["Bsm_ExitDate"] = "Date de sortie",
    ["Bsm_ReasonExit"] = "Motif de sortie",

    // Administration
    ["Adm_Users"] = "Utilisateurs",
    ["Adm_Roles"] = "RÃ´les",
    ["Adm_Parameters"] = "ParamÃ¨tres",
    ["Adm_SpecialApprovers"] = "Approbateurs spÃ©ciaux",
    ["Adm_Contracts"] = "Contrats",
    ["Adm_AuditLog"] = "Journal d'audit",

    // Messages
    ["Msg_ConfirmDelete"] = "ÃŠtes-vous sÃ»r de vouloir supprimer cet Ã©lÃ©ment ?",
    ["Msg_DeleteSuccess"] = "SupprimÃ© avec succÃ¨s.",
    ["Msg_SaveSuccess"] = "EnregistrÃ© avec succÃ¨s.",
    ["Msg_ErrorOccurred"] = "Une erreur s'est produite.",
    ["Msg_AccessDenied"] = "AccÃ¨s refusÃ©. Vous n'Ãªtes pas autorisÃ© Ã  accÃ©der Ã  cette page.",
    ["Msg_PageLoadError"] = "La page n'a pas pu se charger correctement. Veuillez rÃ©essayer.",
    ["Msg_Required"] = "Ce champ est obligatoire.",
    ["Msg_NoDataFound"] = "Aucun rÃ©sultat trouvÃ©.",
    ["Msg_SubmitConfirm"] = "ÃŠtes-vous sÃ»r de vouloir soumettre ce bon pour approbation ?",
    ["Msg_ApproveConfirm"] = "ÃŠtes-vous sÃ»r de vouloir approuver ce bon ?",
    ["Msg_RejectConfirm"] = "ÃŠtes-vous sÃ»r de vouloir rejeter ce bon ?",
    ["Msg_ReturnConfirm"] = "ÃŠtes-vous sÃ»r de vouloir retourner ce bon ?",
    ["Msg_CancelConfirm"] = "ÃŠtes-vous sÃ»r de vouloir annuler ce bon ?",
    ["Msg_Success"] = "OpÃ©ration effectuÃ©e avec succÃ¨s.",
    ["Msg_Error"] = "Une erreur s'est produite.",
    ["Msg_Confirm"] = "ÃŠtes-vous sÃ»r ?",
    ["Msg_Saved"] = "EnregistrÃ© avec succÃ¨s.",
    ["Msg_Deleted"] = "SupprimÃ© avec succÃ¨s.",
    ["Msg_Submitted"] = "Bon d'entrÃ©e soumis pour approbation.",
    ["Msg_Approved"] = "ApprouvÃ© avec succÃ¨s.",
    ["Msg_Rejected"] = "RejetÃ©",
    ["Msg_BonRejected"] = "Le bon d'entrÃ©e a Ã©tÃ© rejetÃ©.",
    ["Msg_Returned"] = "RetournÃ©",
    ["Msg_BonReturned"] = "Le bon d'entrÃ©e a Ã©tÃ© retournÃ© au demandeur.",
    ["Msg_UnexpectedError"] = "Une erreur inattendue s'est produite.",
    ["Msg_LoadFailed"] = "Ã‰chec du chargement :",
    ["Msg_FillRequired"] = "Veuillez remplir tous les champs obligatoires.",

    // Impersonation
    ["Imp_Simulating"] = "simule",
    ["Imp_Stop"] = "ArrÃªter",

    // Erreur
    ["Err_Title"] = "Une erreur s'est produite",
    ["Err_Message"] = "La page n'a pas pu se charger correctement. Veuillez rÃ©essayer.",

    // SÃ©curitÃ©
    ["Sec_Title"] = "SÃ©curitÃ©",
    ["Sec_Scanner"] = "Scanner QR",
    ["Sec_History"] = "Historique des scans",

    // Dashboard
    ["Dash_Title"] = "Tableau de bord",
    ["Dash_Subtitle"] = "Vue d'ensemble en temps rÃ©el des bons d'entrÃ©e et de sortie de matÃ©riels.",
    ["Dash_NewBEM"] = "Nouveau BEM",
    ["Dash_NewBSM"] = "Nouveau BSM",
    ["Dash_VolumeTotal"] = "Volume total",
    ["Dash_Operations"] = "opÃ©rations",
    ["Dash_EntryVouchers"] = "Bons d'entrÃ©e",
    ["Dash_TotalEntries"] = "Total entrÃ©es",
    ["Dash_ExitVouchers"] = "Bons de sortie",
    ["Dash_TotalExits"] = "Total sorties",
    ["Dash_Pending"] = "En attente",
    ["Dash_ToProcess"] = "Ã€ traiter",
    ["Dash_MyRequests"] = "Mes demandes",
    ["Dash_Approved"] = "ApprouvÃ©",
    ["Dash_ThisMonth"] = "Ce mois",
    ["Dash_Rejections"] = "Rejets",
    ["Dash_Unread"] = "non lu(s)",
    ["Dash_AllRead"] = "Tout lu",
    ["Dash_Loans"] = "PrÃªts",
    ["Dash_Overdue"] = "en retard",
    ["Dash_NoOverdue"] = "Aucun retard",
    ["Dash_LiveIndicators"] = "Indicateurs mis Ã  jour en temps rÃ©el",
    ["Dash_GoodMorning"] = "Bonjour",
    ["Dash_GoodAfternoon"] = "Bon aprÃ¨s-midi",
    ["Dash_GoodEvening"] = "Bonsoir",
    ["Dash_WaitingApprover"] = "En attente : Approbateur",
    ["Dash_WaitingGM"] = "En attente : DG",
    ["Dash_WaitingOPJ"] = "En attente : OPJ",
    ["Dash_WaitingID"] = "En attente : Identification",
    ["Dash_WaitingIT"] = "En attente : IT",
    ["Dash_WaitingEnv"] = "En attente : Environnement",

    // SuiviBons
    ["SuiviBons_Title"] = "Suivi de mes bons",
    ["SuiviBons_Subtitle"] = "Suivez l'avancement de vos demandes d'approbation en cours",
    ["SuiviBons_NoPending"] = "Vous n'avez aucun bon en attente d'approbation",
    ["SuiviBons_PendingBEM"] = "Bons d'entrÃ©e en attente",
    ["SuiviBons_PendingBSM"] = "Bons de sortie en attente",

    // ListeBons
    ["ListeBons_Title"] = "Gestion des bons",
    ["ListeBons_Subtitle"] = "TraÃ§abilitÃ© complÃ¨te des bons de matÃ©riels",
    ["ListeBons_NewEntry"] = "Nouveau bon d'entrÃ©e",
    ["ListeBons_NewExit"] = "Nouveau bon de sortie",
    ["ListeBons_DateFrom"] = "Date dÃ©but",
    ["ListeBons_DateTo"] = "Date fin",
    ["ListeBons_NoEntries"] = "Aucun bon d'entrÃ©e trouvÃ©",
    ["ListeBons_NoExits"] = "Aucun bon de sortie trouvÃ©",
    ["ListeBons_NoLoans"] = "Aucun prÃªt trouvÃ©",
    ["ListeBons_Entries"] = "EntrÃ©es",
    ["ListeBons_Exits"] = "Sorties",
    ["ListeBons_LastAction"] = "DerniÃ¨re action",
    ["ListeBons_ViewDetails"] = "Voir dÃ©tails",
    ["ListeBons_ReturnDate"] = "Retour prÃ©vu",
    ["ListeBons_Deadline"] = "Ã‰chÃ©ance",
    ["ListeBons_LoanReturn"] = "Retourner",
    ["ListeBons_Destination"] = "Destinataire",
    ["ListeBons_DateSortie"] = "Date de sortie",
    ["ListeBons_SearchPlaceholder"] = "RÃ©fÃ©rence, sociÃ©tÃ©, demandeur...",

    // BemF
    ["BemF_PageTitleNew"] = "Nouveau bon d'entrÃ©e - KCC Material Flow",
    ["BemF_PageTitleEdit"] = "Modifier bon d'entrÃ©e - KCC Material Flow",
    ["BemF_FormTitle"] = "Bon d'entrÃ©e matÃ©riel",
    ["BemF_CompanyInfo"] = "Informations sociÃ©tÃ©",
    ["BemF_CompanyName"] = "Nom de la sociÃ©tÃ©",
    ["BemF_ContractNumber"] = "NumÃ©ro de contrat (PO)",
    ["BemF_SelectCompany"] = "SÃ©lectionner une sociÃ©tÃ©",
    ["BemF_SelectContract"] = "SÃ©lectionner un contrat",
    ["BemF_ContractorEmail"] = "Adresse e-mail du contractant",
    ["BemF_SiteManager"] = "Responsable de site (Contractant)",
    ["BemF_HostDept"] = "DÃ©partement d'accueil",
    ["BemF_SelectDept"] = "-- SÃ©lectionner le dÃ©partement d'accueil --",
    ["BemF_KccSite"] = "Site KCC",
    ["BemF_SelectSite"] = "-- SÃ©lectionner le site KCC --",
    ["BemF_EntryReason"] = "Motif d'entrÃ©e",
    ["BemF_EscortDetails"] = "DÃ©tails de l'escorte",
    ["BemF_EscortName"] = "Nom",
    ["BemF_EscortFunction"] = "Fonction",
    ["BemF_From"] = "De (Origine)",
    ["BemF_SelectFrom"] = "-- SÃ©lectionner l'origine --",
    ["BemF_To"] = "Vers (Destination)",
    ["BemF_SelectTo"] = "-- SÃ©lectionner la destination --",
    ["BemF_Materials"] = "MatÃ©riels",
    ["BemF_ProductCode"] = "Code produit / NÂ° de sÃ©rie",
    ["BemF_Designation"] = "DÃ©signation",
    ["BemF_Qty"] = "QuantitÃ©",
    ["BemF_Article"] = "article",
    ["BemF_Articles"] = "articles",
    ["BemF_Add"] = "Ajouter",
    ["BemF_Reserves"] = "RÃ©serves Ã©ventuelles",
    ["BemF_ReservesPlaceholder"] = "Observations, rÃ©serves ou commentaires...",
    ["BemF_Draft"] = "Brouillon",
    ["BemF_Submit"] = "Soumettre",
    ["BemF_Review"] = "RÃ©capitulatif",
    ["BemF_ReviewCompany"] = "SociÃ©tÃ©",
    ["BemF_ReviewDept"] = "DÃ©partement d'accueil",
    ["BemF_ReviewReason"] = "Motif d'entrÃ©e",
    ["BemF_ReviewMaterials"] = "MatÃ©riels",
    ["BemF_ReviewEscort"] = "Escorte",
    ["BemF_ReviewValidity"] = "ValiditÃ©",
    ["BemF_NoCompany"] = "Aucune sociÃ©tÃ© sÃ©lectionnÃ©e",
    ["BemF_NoDept"] = "Non dÃ©fini",
    ["BemF_NoReason"] = "Aucun motif",
    ["BemF_NoMaterial"] = "Aucun matÃ©riel saisi",
    ["BemF_NoEscort"] = "Non renseignÃ©",
    ["BemF_NoDesig"] = "(Sans dÃ©signation)",
    ["BemF_MoreItems"] = "autres...",
    ["BemF_TotalEntries"] = "Total : {0} articles",
    ["BemF_ValidUntil"] = "Expire le :",
    ["BemF_LoadingError"] = "Chargement...",
    ["BemF_NotFound"] = "Bon d'entrÃ©e introuvable",
    ["BemF_CannotEdit"] = "Ce bon ne peut plus Ãªtre modifiÃ©",
    ["BemF_CannotEditMsg"] = "Seuls les bons en brouillon peuvent Ãªtre modifiÃ©s.",
    ["BemF_CreatedOn"] = "CrÃ©Ã© le :",
    ["BemF_SaveChanges"] = "Enregistrer les modifications",
    ["BemF_Saving"] = "Enregistrement...",
    ["BemF_AdditionalDesc"] = "Description complÃ©mentaire",
    ["BemF_AddInfoPlaceholder"] = "Informations complÃ©mentaires...",
    ["BemF_NoMaterialAdded"] = "Aucun matÃ©riel ajoutÃ©",
    ["BemF_SiteManagerPlaceholder"] = "Nom du responsable de site",
    ["BemF_HostDeptPlaceholder"] = "Saisir le dÃ©partement d'accueil",
    ["BemF_ReasonSitePlaceholder"] = "Motif de la visite",
    ["BemF_Expires"] = "Expire le :",

    // BemV
    ["BemV_EntryPermit"] = "BON D'ENTRÃ‰E MATÃ‰RIEL",
    ["BemV_PropertyEntry"] = "Permis d'entrÃ©e de propriÃ©tÃ©",
    ["BemV_TypeEntry"] = "EntrÃ©e",
    ["BemV_Loading"] = "Chargement du bon...",
    ["BemV_AccessDenied"] = "AccÃ¨s refusÃ©",
    ["BemV_AccessDeniedMsg"] = "Vous n'Ãªtes pas autorisÃ© Ã  consulter ce bon.",
    ["BemV_NotFound"] = "Bon introuvable",
    ["BemV_CreatedAt"] = "CrÃ©Ã© le",
    ["BemV_Edit"] = "Modifier",
    ["BemV_Delete"] = "Supprimer",
    ["BemV_Submit"] = "Soumettre",
    ["BemV_Approve"] = "Approuver",
    ["BemV_Reject"] = "Rejeter",
    ["BemV_Print"] = "Imprimer",
    ["BemV_DownloadPDF"] = "TÃ©lÃ©charger PDF",
    ["BemV_VisitorInfo"] = "Informations du visiteur",
    ["BemV_Materiels"] = "MatÃ©riels",
    ["BemV_Workflow"] = "Flux d'approbation",
    ["BemV_AssocBSE"] = "Bon de sortie associÃ© :",
    ["BemV_Qty"] = "QTÃ‰",
    ["BemV_Serial"] = "NÂ° SÃ‰RIE",
    ["BemV_QtySortie"] = "QTÃ‰ SORTIE",
    ["BemV_Solde"] = "SOLDE",
    ["BemV_Available"] = "Disponible",
    ["BemV_Partial"] = "Partiel",
    ["BemV_Exhausted"] = "Ã‰puisÃ©",
    ["BemV_TotalEntry"] = "Total entrÃ©e :",
    ["BemV_TotalExit"] = "Total sortie :",
    ["BemV_Balance"] = "Solde :",
    ["BemV_ReturnModif"] = "RetournÃ© pour modification â€”",
    ["BemV_AtPending"] = "Au niveau {0}",
    ["BemV_RejectDetails"] = "Voir dÃ©tails du rejet",
    ["BemV_PreMigration"] = "Workflow prÃ©-migration",
    ["BemV_Pending"] = "En attente",
    ["BemV_OneOf"] = "l'un de :",

    // Dialogues
    ["Dlg_ApproveDesc"] = "Vous Ãªtes sur le point d'approuver ce bon d'entrÃ©e.",
    ["Dlg_ReturnDesc"] = "Ce bon sera retournÃ© au demandeur pour modification. Veuillez indiquer les corrections nÃ©cessaires.",
    ["Dlg_RejectDesc"] = "Ce bon sera dÃ©finitivement rejetÃ©. Cette action est irrÃ©versible.",
    ["Dlg_RejectLabel"] = "Motif du rejet *",
    ["Dlg_ReturnLabel"] = "Motif du retour",
    ["Dlg_ApproveLabel"] = "Commentaire (optionnel)",
    ["Dlg_RejectPlaceholder"] = "Expliquer le motif du rejet...",
    ["Dlg_ReturnPlaceholder"] = "Indiquer les corrections nÃ©cessaires...",
    ["Dlg_ApprovePlaceholder"] = "Ajouter un commentaire (optionnel)...",
    ["Dlg_RejectRequired"] = "Le motif du rejet est obligatoire.",
    ["Dlg_Approve"] = "Approuver",
    ["Dlg_Return"] = "Retourner",
    ["Dlg_Reject"] = "Rejeter",
    ["Dlg_Confirm"] = "Confirmer",
    ["Dlg_ApproveTitle"] = "Confirmer l'approbation",
    ["Dlg_RejectTitle"] = "Confirmer le rejet",
    ["Dlg_ApproveComment"] = "Commentaire / Observations *",
    ["Dlg_RejectReason"] = "Motif du rejet *",
    ["Dlg_ApproveCommentPlaceholder"] = "Saisir vos observations ou commentaires...",
    ["Dlg_RejectReasonPlaceholder"] = "Veuillez indiquer le motif du rejet...",
    ["Dlg_ApproveCommentRequired"] = "Un commentaire est requis",
    ["Dlg_RejectReasonRequired"] = "Le motif du rejet est obligatoire",
    ["Dlg_ReturnReason"] = "Motif du retour",
    ["Dlg_OptionalComment"] = "Commentaire (optionnel)",
    ["Dlg_ExplainRejection"] = "Expliquer le motif du rejet...",
    ["Dlg_IndicateCorrections"] = "Indiquer les corrections nÃ©cessaires...",
    ["Dlg_AddComment"] = "Ajouter un commentaire...",
    ["Dlg_ExplainReason"] = "Expliquer le motif...",
    ["Dlg_RejectReasonMandatory"] = "Le motif du rejet est obligatoire.",
    ["Dlg_IndicateReason"] = "Veuillez indiquer le motif.",
    ["Dlg_CommentLabel"] = "Commentaire (optionnel)",
    ["Dlg_CommentPlaceholder"] = "Ajouter un commentaire...",

    // Approbations
    ["Appro_Title"] = "Mes approbations",
    ["Appro_Subtitle"] = "Bons en attente de votre validation",
    ["Appro_EntryVouchers"] = "Bons d'entrÃ©e",
    ["Appro_ExitVouchers"] = "Bons de sortie",
    ["Appro_TotalPending"] = "Total en attente",
    ["Appro_ActiveFilter"] = "Filtre actif :",
    ["Appro_LoadingApprovals"] = "Chargement des approbations...",
    ["Appro_NoPending"] = "Aucune approbation en attente",
    ["Appro_NoPendingDesc"] = "Vous n'avez aucun bon Ã  valider pour le moment.",
    ["Appro_SearchPlaceholder"] = "Rechercher par rÃ©fÃ©rence, demandeur, destination...",
    ["Appro_ClearSearch"] = "Effacer la recherche",
    ["Appro_Materials"] = "MatÃ©riels",
    ["Appro_EntryType"] = "EntrÃ©e",
    ["Appro_ExitType"] = "Sortie",
    ["Appro_ApprovedReprint"] = "Bons approuvÃ©s â€” RÃ©impression",
    ["Appro_ApprovedReprintDesc"] = "Ces bons ont Ã©tÃ© approuvÃ©s Ã  votre niveau. Vous pouvez les rÃ©imprimer Ã  tout moment.",
    ["Appro_Reprint"] = "RÃ©imprimer",

    // Rejets
    ["Rejets_Title"] = "Liste des rejets",
    ["Rejets_Subtitle"] = "Consultez les bons rejetÃ©s et leurs motifs",
    ["Rejets_MarkAllRead"] = "Tout marquer comme lu",
    ["Rejets_Unread"] = "Non lu",
    ["Rejets_Read"] = "Lu",
    ["Rejets_Loading"] = "Chargement des rejets...",
    ["Rejets_None"] = "Aucun rejet",
    ["Rejets_NoneDesc"] = "Aucun bon rejetÃ© ne correspond aux critÃ¨res.",
    ["Rejets_SearchPlaceholder"] = "Rechercher par rÃ©fÃ©rence, approbateur, motif...",
    ["Rejets_RejectedBy"] = "RejetÃ© par",
    ["Rejets_Step"] = "Ã‰tape",
    ["Rejets_Reason"] = "Motif",
    ["Rejets_New"] = "Nouveau",
    ["Rejets_Detail"] = "DÃ©tail",
    ["Rejets_RejectionDetails"] = "DÃ©tails du rejet",
    ["Rejets_FullReason"] = "Motif complet :",

    // AccDen
    ["AccDen_Title"] = "AccÃ¨s refusÃ©",
    ["AccDen_Message"] = "Votre compte ne dispose pas des autorisations nÃ©cessaires pour accÃ©der Ã  KCC Material Flow. Pour demander l'accÃ¨s, veuillez soumettre une demande via le portail ServiceNow.",
    ["AccDen_Step1_Title"] = "Ouvrir ServiceNow",
    ["AccDen_Step2_Title"] = "Soumettre la demande",
    ["AccDen_Step3_Title"] = "Attendre l'approbation",
    ["AccDen_Step3_Desc"] = "Notification par e-mail.",
    ["AccDen_RequestAccess"] = "Demander l'accÃ¨s",
    ["AccDen_Help"] = "Besoin d'aide ? Contactez votre administrateur IT â€”",
    ["Ad_PageTitle"] = "AccÃ¨s refusÃ© â€” KCC Material Flow",
    ["Ad_Title"] = "AccÃ¨s refusÃ©",
    ["Ad_Subtitle"] = "Votre compte ne dispose pas des autorisations nÃ©cessaires pour accÃ©der Ã  KCC Material Flow. Pour demander l'accÃ¨s, veuillez soumettre une demande via le portail ServiceNow.",
    ["Ad_Step1Title"] = "Ouvrir ServiceNow",
    ["Ad_Step2Title"] = "Soumettre la demande",
    ["Ad_Step3Title"] = "Attendre l'approbation",
    ["Ad_RequestAccess"] = "Demander l'accÃ¨s",
    ["Ad_Help"] = "Besoin d'aide ? Contactez votre administrateur IT â€”",

    // AdmNav
    ["AdmNav_Roles"] = "RÃ´les",
    ["AdmNav_SpecialApprovers"] = "Approbateurs spÃ©ciaux",
    ["AdmNav_Parameters"] = "ParamÃ¨tres",

    // Scanner
    ["Scan_Title"] = "Scanner de code QR",
    ["Scan_Subtitle"] = "Scannez le code QR du bon de matÃ©riel pour valider le passage",
    ["Scan_ActiveBarriere"] = "Checkpoint actif",
    ["Scan_SelectBarriere"] = "SÃ©lectionnez votre checkpoint...",
    ["Scan_ManualEntry"] = "Saisie manuelle",
    ["Scan_CameraInactive"] = "CamÃ©ra inactive",
    ["Scan_ActivateCamera"] = "Activer la camÃ©ra",
    ["Scan_Prompt"] = "Saisir le code QR ou le numÃ©ro de rÃ©fÃ©rence du bon :",
    ["Scan_CodePlaceholder"] = "Code QR ou numÃ©ro de rÃ©fÃ©rence...",
    ["Scan_ValidateCode"] = "Valider le code",
    ["Scan_AccessGranted"] = "ACCÃˆS ACCORDÃ‰",
    ["Scan_AccessDenied"] = "ACCÃˆS REFUSÃ‰",
    ["Scan_Origin"] = "Origine (DE)",
    ["Scan_MaterialCount"] = "Nombre de matÃ©riels",
    ["Scan_ConfirmPassage"] = "Confirmer le passage",
    ["Scan_ReportAnomaly"] = "Signaler une anomalie",
    ["Scan_ReportToSupervisor"] = "Signaler au superviseur",
    ["Scan_ObservationsPlaceholder"] = "Ajouter des observations...",
    ["Scan_StartMsg"] = "Veuillez sÃ©lectionner votre checkpoint pour commencer le scan",
    ["Scan_NewScan"] = "Nouveau scan",
    ["Scan_DocumentAnormal"] = "Document anormal - AccÃ¨s impossible",
    ["Scan_DocumentExpired"] = "Document expirÃ© - AccÃ¨s refusÃ©",
    ["Scan_DocumentUsed"] = "Document dÃ©jÃ  utilisÃ© Ã  ce checkpoint",
    ["Scan_DocumentNotFound"] = "Document introuvable - AccÃ¨s impossible",
    ["Scan_UnauthorizedCheckpoint"] = "Checkpoint non autorisÃ© pour ce document",
    ["Scan_PassageProof"] = "Preuve de passage",
    ["Scan_SignalAnomaly"] = "Signaler une anomalie",

    // Sqr
    ["Sqr_Title"] = "Scanner un code QR",
    ["Sqr_Subtitle"] = "Scannez le code QR du document de matÃ©riel pour valider le passage",
    ["Sqr_BarriereTitle"] = "BarriÃ¨re active",
    ["Sqr_BarrierePlaceholder"] = "SÃ©lectionnez votre barriÃ¨re...",
    ["Sqr_Btn_Camera"] = "CamÃ©ra",
    ["Sqr_Btn_Manual"] = "Saisie manuelle",
    ["Sqr_CameraOff"] = "CamÃ©ra inactive",
    ["Sqr_Btn_StartCamera"] = "Activer la camÃ©ra",
    ["Sqr_Btn_StopCamera"] = "ArrÃªter",
    ["Sqr_ManualHint"] = "Saisir le code QR ou le numÃ©ro de rÃ©fÃ©rence du document :",
    ["Sqr_ManualPlaceholder"] = "Code QR ou numÃ©ro de rÃ©fÃ©rence...",
    ["Sqr_Btn_ValidateCode"] = "Valider le code",
    ["Sqr_AccessGranted"] = "ACCÃˆS ACCORDÃ‰",
    ["Sqr_AccessDenied"] = "ACCÃˆS REFUSÃ‰",
    ["Sqr_Col_Reference"] = "RÃ©fÃ©rence",
    ["Sqr_Col_From"] = "Origine (DE)",
    ["Sqr_Col_To"] = "Destination (VERS)",
    ["Sqr_Col_Materials"] = "Nombre de matÃ©riels",
    ["Sqr_Col_Expiry"] = "Expiration",
    ["Sqr_Btn_ConfirmPassage"] = "Confirmer le passage",
    ["Sqr_Btn_SignalAnomaly"] = "Signaler une anomalie",
    ["Sqr_Reason"] = "Motif :",
    ["Sqr_AnomaliesDetected"] = "Anomalies dÃ©tectÃ©es :",
    ["Sqr_Btn_NewScan"] = "Nouveau scan",
    ["Sqr_Btn_ReportSupervisor"] = "Signaler au superviseur",
    ["Sqr_ObsLabel"] = "Observations (optionnel)",
    ["Sqr_ObsPlaceholder"] = "Ajouter des observations...",
    ["Sqr_SelectBarriere"] = "Veuillez sÃ©lectionner votre barriÃ¨re pour commencer le scan",

    // Anomalies
    ["Anomalies_Title"] = "Gestion des anomalies",
    ["Anomalies_Subtitle"] = "Suivi et traitement des anomalies signalÃ©es",
    ["Anomalies_CriticalSeverity"] = "SÃ©vÃ©ritÃ© critique",
    ["Anomalies_HighSeverity"] = "SÃ©vÃ©ritÃ© Ã©levÃ©e",
    ["Anomalies_AllTypes"] = "Tous les types",
    ["Anomalies_AllStatuses"] = "Tous les statuts",
    ["Anomalies_From"] = "De",
    ["Anomalies_To"] = "Ã€",
    ["Anomalies_Treated"] = "TraitÃ©",
    ["Anomalies_Pending"] = "En attente",
    ["Anomalies_Process"] = "Traiter",
    ["Anomalies_ActiveFilter"] = "Filtre actif :",
    ["Anl_Title"] = "Gestion des anomalies",
    ["Anl_Subtitle"] = "Suivi et traitement des anomalies signalÃ©es",
    ["Anl_Btn_Dashboard"] = "Tableau de bord",
    ["Anl_Btn_Export"] = "Exporter",
    ["Anl_FilterActive"] = "Filtre actif :",
    ["Anl_GravCritique"] = "SÃ©vÃ©ritÃ© critique",
    ["Anl_GravElevee"] = "SÃ©vÃ©ritÃ© Ã©levÃ©e",
    ["Anl_SearchPlaceholder"] = "Rechercher par rÃ©fÃ©rence, description...",
    ["Anl_PlaceholderType"] = "Tous les types",
    ["Anl_PlaceholderStatut"] = "Tous les statuts",
    ["Anl_Col_Severity"] = "SÃ©vÃ©ritÃ©",
    ["Anl_Col_Type"] = "Type",
    ["Anl_Col_Document"] = "Document",
    ["Anl_Col_Description"] = "Description",
    ["Anl_Col_Statut"] = "Statut",
    ["Anl_Statut_Traitee"] = "RÃ©solu",
    ["Anl_Statut_EnAttente"] = "En attente",
    ["Anl_Btn_ViewDetail"] = "Voir",
    ["Anl_Btn_Process"] = "Traiter",
    ["Anl_Lbl_Barrier"] = "BarriÃ¨re :",
    ["Anl_Lbl_Description"] = "Description :",

    // Ano types
    ["Ano_BarriereNonAutorisee"] = "BarriÃ¨re non autorisÃ©e",
    ["Ano_DocumentExpire"] = "Document expirÃ©",
    ["Ano_DocumentInexistant"] = "Document manquant",
    ["Ano_ScanDuplique"] = "Scan dupliquÃ©",
    ["Ano_QRCodeInvalide"] = "Code QR invalide",
    ["Ano_ItineraireNonRespectee"] = "ItinÃ©raire non respectÃ©",
    ["Ano_SignalementManuel"] = "Signalement manuel",

    // GravitÃ©
    ["Grav_Faible"] = "Faible",
    ["Grav_Moyen"] = "Moyen",
    ["Grav_Eleve"] = "Ã‰levÃ©",
    ["Grav_Critique"] = "Critique",

    // Scan statuts
    ["Scan_Statut_Valid"] = "Scan valide",
    ["Scan_Statut_Invalid"] = "Document invalide",
    ["Scan_Statut_Anomaly"] = "Anomalie",
    ["Scan_Statut_Expired"] = "Document expirÃ©",
    ["Scan_Statut_AlreadyUsed"] = "DÃ©jÃ  scannÃ©",
    ["Scan_Statut_NotFound"] = "Document introuvable",
    ["Scan_Statut_Unknown"] = "Statut inconnu",

    // Historique
    ["History_Title"] = "Historique des scans",
    ["History_Subtitle"] = "Liste complÃ¨te des mouvements de matÃ©riels",
    ["History_AllCheckpoints"] = "Tous les checkpoints",
    ["History_Movement"] = "Mouvement",
    ["Hsc_Title"] = "Historique des scans",
    ["Hsc_Subtitle"] = "Liste complÃ¨te des mouvements de matÃ©riels",
    ["Hsc_Btn_Scan"] = "Scanner QR",
    ["Hsc_SearchPlaceholder"] = "Rechercher par rÃ©fÃ©rence, agent...",
    ["Hsc_PlaceholderBarriere"] = "Toutes les barriÃ¨res",
    ["Hsc_Col_Movement"] = "Mouvement",
    ["Hsc_Col_Barrier"] = "BarriÃ¨re",
    ["Hsc_Col_Agent"] = "Agent",
    ["Hsc_Col_Anomaly"] = "Anomalie",
    ["Hsc_Filter_Valid"] = "Scans valides",
    ["Hsc_Filter_Invalid"] = "Scans invalides",
    ["Hsc_Filter_Anomaly"] = "Avec anomalies",

    // Grid
    ["Grid_Loading"] = "Chargement des donnÃ©es...",
    ["Grid_Paging"] = "Page {0} sur {1} ({2} Ã©lÃ©ments)",
    ["Grid_Empty"] = "Aucun Ã©lÃ©ment trouvÃ©.",

    // Utilisateurs
    ["Users_HrSource"] = "Source = base de donnÃ©es RH. Seuls les employÃ©s ayant un compte Windows peuvent accÃ©der Ã  l'application.",
    ["Users_ActiveDesc"] = "Actif = compte Windows prÃ©sent.",
    ["Users_InactiveDesc"] = "Inactif = pas de compte Windows.",
    ["Users_Shown"] = "affichÃ©s â€” rechercher pour en voir plus",
    ["Users_NoEmployee"] = "Aucun employÃ©.",
    ["Users_Manager"] = "Responsable (HOD)",
    ["Users_RevokeAccess"] = "RÃ©voquer l'accÃ¨s Ã  l'application",
    ["Users_GrantAccess"] = "Accorder l'accÃ¨s Ã  l'application",
    ["Usr_BtnNew"] = "Nouvel utilisateur",
    ["Usr_SearchPh"] = "Matricule, nom, loginâ€¦ (min. 1 car.)",
    ["Usr_FilterAllDepts"] = "Tous les dÃ©partements",
    ["Usr_FilterPh"] = "Filtrer",
    ["Usr_Hint"] = "Source = rÃ©pertoire RH. Seuls les employÃ©s ayant un compte Windows peuvent accÃ©der Ã  l'application. Actif = compte Windows prÃ©sent. Inactif = pas de compte Windows.",
    ["Usr_Shown"] = "affichÃ©s â€” rechercher pour en voir plus",
    ["Usr_Empty"] = "Aucun employÃ©.",
    ["Usr_ColManager"] = "Responsable (HOD)",
    ["Usr_ColAdminLevel"] = "Niveau admin",
    ["Usr_TitleRevoke"] = "RÃ©voquer l'accÃ¨s Ã  l'application",
    ["Usr_TitleGrant"] = "Accorder l'accÃ¨s Ã  l'application",
    ["Usr_TitleDelete"] = "Supprimer cet utilisateur autonome",

    // RÃ´les
    ["Roles_StandardUser"] = "Utilisateur standard",
    ["Roles_StandardUserDesc"] = "Peut crÃ©er et soumettre des bons d'entrÃ©e et de sortie de matÃ©riels. ReÃ§oit des notifications de suivi sur ses bons.",
    ["Rol_Title"] = "RÃ´les & AccÃ¨s",
    ["Rol_Subtitle"] = "Vue d'ensemble des niveaux d'accÃ¨s et des utilisateurs avec des droits administratifs.",
    ["Rol_BtnManageUsers"] = "GÃ©rer les utilisateurs",
    ["Rol_SecRoleDef"] = "DÃ©finitions des rÃ´les",
    ["Rol_BadgeNone"] = "Aucun",
    ["Rol_SubStandard"] = "Utilisateur standard",
    ["Rol_DescStandard"] = "Peut crÃ©er et soumettre des bons d'entrÃ©e et de sortie de matÃ©riels. ReÃ§oit des notifications de suivi.",
    ["Rol_SubAdmin"] = "Administrateur",
    ["Rol_DescAdmin"] = "AccÃ¨s Ã  l'espace Admin. Peut gÃ©rer les utilisateurs, configurer les workflows et les paramÃ¨tres systÃ¨me. Ne peut pas modifier les SuperAdmins.",
    ["Rol_SubSuperAdmin"] = "Super Administrateur",
    ["Rol_DescSuperAdmin"] = "AccÃ¨s complet sans restriction. GÃ¨re Admin et SuperAdmin, utilise l'impersonation et accÃ¨de aux journaux d'audit complets.",
    ["Rol_BadgeApprover"] = "Approbateur",

    // Adm pages
    ["Adm_NewUser"] = "Nouvel utilisateur",
    ["Adm_SearchPlaceholder"] = "Matricule, nom, loginâ€¦ (min. 1 car.)",
    ["Adm_AllDepts"] = "Tous les dÃ©partements",
    ["Adm_FullName"] = "Nom complet",
    ["Adm_WindowsLogin"] = "Identifiant Windows",
    ["Adm_AdminLevel"] = "Niveau admin",
    ["Adm_DeleteStandalone"] = "Supprimer utilisateur autonome",
    ["Adm_WorkflowTitle"] = "Flux d'approbation",
    ["Adm_WorkflowDesc"] = "Configurer la chaÃ®ne d'approbation par dÃ©partement. Un workflow spÃ©cifique remplace le workflow gÃ©nÃ©rique.",
    ["Adm_SpecificWorkflow"] = "SpÃ©cifique",
    ["Adm_OwnDeptConfig"] = "Configuration propre au dÃ©partement",
    ["Adm_Inherited"] = "HÃ©ritÃ©",
    ["Adm_UsesGeneric"] = "Utilise le workflow gÃ©nÃ©rique",
    ["Adm_Default"] = "Par dÃ©faut",
    ["Adm_ResetWorkflow"] = "RÃ©initialiser le workflow",
    ["Adm_SpecialApproversTitle"] = "Approbateurs spÃ©ciaux",
    ["Adm_SpecialApproversDesc"] = "DÃ©finit les employÃ©s Superintendent / OPJ / Identification utilisÃ©s en fin de chaÃ®ne d'approbation.",
    ["Adm_NoSpecialApprovers"] = "Aucun approbateur spÃ©cial dÃ©fini. Cliquez sur Ajouter pour commencer.",
    ["Adm_AddSpecialApprover"] = "Ajouter un approbateur spÃ©cial",
    ["Adm_AuditTitle"] = "Journal d'audit",
    ["Adm_AuditDesc"] = "TraÃ§abilitÃ© des actions effectuÃ©es dans le systÃ¨me",
    ["Adm_ActionType"] = "Type d'action",
    ["Adm_CategoryFilter"] = "CatÃ©gorie",
    ["Adm_NoLogs"] = "Aucun journal trouvÃ©",
    ["Adm_ViewChanges"] = "Voir les modifications",
    ["Adm_ParametersTitle"] = "ParamÃ¨tres systÃ¨me",
    ["Adm_ParametersDesc"] = "Configuration des paramÃ¨tres systÃ¨me organisÃ©s par catÃ©gorie",
    ["Adm_NewParam"] = "Nouveau paramÃ¨tre",
    ["Adm_SearchParams"] = "Rechercher (clÃ©, description)...",
    ["Adm_AllCategories"] = "Toutes les catÃ©gories",
    ["Adm_NoParams"] = "Aucun paramÃ¨tre",
    ["Adm_RolesTitle"] = "RÃ´les & AccÃ¨s",
    ["Adm_RolesDesc"] = "Vue d'ensemble des niveaux d'accÃ¨s et des utilisateurs avec des droits administratifs.",
    ["Adm_ManageUsers"] = "GÃ©rer les utilisateurs",
    ["Adm_RolesDefinition"] = "DÃ©finitions des rÃ´les",
    ["Adm_TypesTitle"] = "Gestion des types de matÃ©riels",
    ["Adm_NewType"] = "Nouveau type",
    ["Adm_ApprovalLevels"] = "Niveaux d'approbation",
    ["Adm_DefaultWorkflowDesc"] = "Workflow codÃ© (SUPERINTENDENT â†’ DG â†’ OPJ â†’ IDENTIFICATION)",

    // Wfl
    ["Wfl_Title"] = "Flux d'approbation",
    ["Wfl_Subtitle"] = "Configurer la chaÃ®ne d'approbation par dÃ©partement. Un workflow spÃ©cifique est prioritaire sur le gÃ©nÃ©rique.",
    ["Wfl_BadgeSpecific"] = "SpÃ©cifique",
    ["Wfl_LegendSpecific"] = "Config propre au dÃ©partement",
    ["Wfl_BadgeInherited"] = "HÃ©ritÃ©",
    ["Wfl_LegendInherited"] = "Utilise le workflow gÃ©nÃ©rique",
    ["Wfl_BadgeDefault"] = "Par dÃ©faut",
    ["Wfl_LegendDefault"] = "Workflow codÃ© (SUPERINTENDENT â†’ DG â†’ OPJ â†’ IDENTIFICATION)",

    // Wdg
    ["Wdg_ColDept"] = "DÃ©partement",
    ["Wdg_ColEmployees"] = "EmployÃ©s",
    ["Wdg_ColConfig"] = "Config",
    ["Wdg_ColChain"] = "ChaÃ®ne d'approbation",
    ["Wdg_NoSteps"] = "Aucune Ã©tape",
    ["Wdg_BtnConfigure"] = "Configurer",
    ["Wdg_TitleReset"] = "Supprimer la config spÃ©cifique (hÃ©rite du gÃ©nÃ©rique)",

    // Wfa
    ["Wfa_Title"] = "Approbateurs spÃ©ciaux",
    ["Wfa_Subtitle"] = "DÃ©finit les employÃ©s Superintendent / OPJ / Identification utilisÃ©s en fin de chaÃ®ne d'approbation.",
    ["Wfa_BtnAdd"] = "Ajouter",
    ["Wfa_ActiveCount"] = "actif(s) sur",
    ["Wfa_AllSites"] = "Tous les sites",
    ["Wfa_ActiveBadge"] = "actif(s)",
    ["Wfa_Order"] = "â€¢ Ordre",
    ["Wfa_Inactive"] = "â€¢ Inactif",

    // Types matÃ©riels
    ["Types_Level"] = "niveau(x)",
    ["Tma_Title"] = "Gestion des types de matÃ©riels",
    ["Tma_BtnNew"] = "Nouveau type",
    ["Tma_FilterActive"] = "Actif",
    ["Tma_FilterInactive"] = "Inactif",
    ["Tma_SearchPh"] = "Code, nom, catÃ©gorie...",
    ["Tma_FilterAllCategories"] = "Toutes les catÃ©gories",
    ["Tma_Empty"] = "Aucun type trouvÃ©",
    ["Tma_ColType"] = "Type",
    ["Tma_ColCategory"] = "CatÃ©gorie",
    ["Tma_ColApprovals"] = "Approbations",
    ["Tma_ColValidity"] = "ValiditÃ©",
    ["Tma_ColRequired"] = "Requis",
    ["Tma_Levels"] = "niveau(x)",
    ["Tma_DaysMax"] = "j / max",
    ["Tma_DaysUnit"] = "j",
    ["Tma_BadgeDept"] = "Dept",
    ["Tma_BadgeDir"] = "Dir",
    ["Tma_BadgeSerial"] = "NÂ° sÃ©rie",
    ["Tma_BadgePhoto"] = "Photo",
    ["Tma_BadgeActive"] = "Actif",
    ["Tma_BadgeInactive"] = "Inactif",

    // ParamÃ¨tres
    ["Par_Title"] = "ParamÃ¨tres systÃ¨me",
    ["Par_Subtitle"] = "ParamÃ¨tres systÃ¨me organisÃ©s par catÃ©gorie",
    ["Par_BtnNew"] = "Nouveau paramÃ¨tre",
    ["Par_SearchPh"] = "Rechercher (clÃ©, description)...",
    ["Par_FilterAllCategories"] = "Toutes les catÃ©gories",
    ["Par_Empty"] = "Aucun paramÃ¨tre trouvÃ©",
    ["Par_LblDescription"] = "Description",
    ["Par_LblMetadata"] = "MÃ©tadonnÃ©es",
    ["Par_LblType"] = "Type :",
    ["Par_LblConstraints"] = "Contraintes :",
    ["Par_LblEditable"] = "Modifiable :",
    ["Par_LblSystem"] = "SystÃ¨me :",
    ["Par_Yes"] = "Oui",
    ["Par_No"] = "Non",
    ["Par_ColKey"] = "ClÃ©",
    ["Par_ColDescription"] = "Description",
    ["Par_ColValue"] = "Valeur",
    ["Par_BadgeSystem"] = "SystÃ¨me",

    // Audit log
    ["Aul_Title"] = "Journal d'audit",
    ["Aul_Subtitle"] = "TraÃ§abilitÃ© des actions systÃ¨me",
    ["Aul_FilterUser"] = "Utilisateur",
    ["Aul_FilterActionType"] = "Type d'action",
    ["Aul_FilterAllActions"] = "Tous",
    ["Aul_FilterCategory"] = "CatÃ©gorie",
    ["Aul_FilterAllCategories"] = "Toutes",
    ["Aul_BtnSearch"] = "Rechercher",
    ["Aul_BtnReset"] = "RÃ©initialiser",
    ["Aul_Empty"] = "Aucun journal trouvÃ©",
    ["Aul_LblDescription"] = "Description",
    ["Aul_LblEntity"] = "EntitÃ© :",
    ["Aul_LblContext"] = "Contexte",
    ["Aul_LblIP"] = "IP :",
    ["Aul_BtnViewChanges"] = "Voir les modifications",
    ["Aul_ColDate"] = "Date",
    ["Aul_ColUser"] = "Utilisateur",
    ["Aul_ColAction"] = "Action",
    ["Aul_ColCategory"] = "CatÃ©gorie",
    ["Aul_ColDescription"] = "Description",
    ["Aul_ColLevel"] = "Niveau",

    // Statuts admin
    ["Sta_Title"] = "Gestion des statuts",
    ["Sta_Count"] = "statut(s) sur",
    ["Sta_BtnNew"] = "Nouveau statut",
    ["Sta_FilterActifs"] = "Actifs",
    ["Sta_FilterSystem"] = "SystÃ¨me",
    ["Sta_FilterFinal"] = "Final",
    ["Sta_SearchPh"] = "Rechercher par code, libellÃ©, description...",
    ["Sta_FilterAllTypes"] = "Tous les types de bons",
    ["Sta_Empty"] = "Aucun statut trouvÃ©",
    ["Sta_ColStatut"] = "Statut",
    ["Sta_ColTypeBon"] = "Type de bon",
    ["Sta_ColDescription"] = "Description",
    ["Sta_ColProprietes"] = "PropriÃ©tÃ©s",
    ["Sta_BadgeSystem"] = "SystÃ¨me",
    ["Sta_BadgeFinal"] = "Final",
    ["Sta_BadgeActionReq"] = "Action req.",
    ["Sta_BadgeActif"] = "Actif",
    ["Sta_BadgeInactif"] = "Inactif",

    // Tooltips
    ["Tt_Disable"] = "DÃ©sactiver",
    ["Tt_Enable"] = "Activer",

    // BSM Form
    ["BsmF_PageTitleNew"] = "Nouveau bon de sortie - KCC Material Flow",
    ["BsmF_PageTitleEdit"] = "Modifier bon de sortie - KCC Material Flow",
    ["BsmF_FormTitle"] = "Bon de sortie matÃ©riel",
    ["BsmF_FormSubtitle"] = "Permis de sortie de propriÃ©tÃ©",
    ["BsmF_RequesterInfo"] = "Informations du demandeur",
    ["BsmF_NameLabel"] = "Nom",
    ["BsmF_NamePlaceholder"] = "Nom complet",
    ["BsmF_FunctionLabel"] = "Fonction",
    ["BsmF_FunctionPlaceholder"] = "Fonction",
    ["BsmF_DeptLabel"] = "DÃ©partement",
    ["BsmF_DeptPlaceholder"] = "DÃ©partement",
    ["BsmF_SiteSection"] = "Site KCC & Demande pour",
    ["BsmF_RequestFor"] = "Demande pour (EmployÃ©)",
    ["BsmF_SearchEmployee"] = "Rechercher par nom, code ou login...",
    ["BsmF_ExitType"] = "Type de bon de sortie",
    ["BsmF_SelectTypeContinue"] = "SÃ©lectionnez le type de bon de sortie pour continuer.",
    ["BsmF_BemSource"] = "Bon d'entrÃ©e source (BEM)",
    ["BsmF_SearchApprovedBem"] = "Rechercher un bon d'entrÃ©e approuvÃ©",
    ["BsmF_SearchBemPlaceholder"] = "Rechercher par numÃ©ro, sociÃ©tÃ© ou dÃ©partement...",
    ["BsmF_NoBemAvailable"] = "Aucun bon d'entrÃ©e approuvÃ© disponible.",
    ["BsmF_Linked"] = "LiÃ©",
    ["BsmF_Reason"] = "Motif",
    ["BsmF_ReasonPlaceholder"] = "DÃ©crire le motif de sortie...",
    ["BsmF_ReturnDate"] = "Date de retour prÃ©vue",
    ["BsmF_SelectReturnDate"] = "SÃ©lectionner la date de retour",
    ["BsmF_OriginDest"] = "Origine / Destination",
    ["BsmF_SelectOrigin"] = "-- SÃ©lectionner l'origine --",
    ["BsmF_SelectDest"] = "-- SÃ©lectionner la destination --",
    ["BsmF_SourceFromBem"] = "L'origine est dÃ©finie par le BEM source.",
    ["BsmF_ExternalReason"] = "Motif - EXTERNE",
    ["BsmF_Checkpoints"] = "Checkpoints",
    ["BsmF_InProgress"] = "En cours...",
    ["BsmF_SelectBemMaterials"] = "SÃ©lectionner les matÃ©riels du BEM source",
    ["BsmF_SerialColTitle"] = "Code produit / NÂ° de sÃ©rie",
    ["BsmF_AddMaterialsBelow"] = "Ajouter des matÃ©riels ci-dessous",
    ["BsmF_ModalTitle"] = "SÃ©lection de matÃ©riels",
    ["BsmF_NbSelected"] = "sÃ©lectionnÃ©(s)",
    ["BsmF_NoMaterialAvail"] = "Aucun matÃ©riel disponible.",
    ["BsmF_ReviewDemandeur"] = "Demandeur",
    ["BsmF_ReviewNotFilled"] = "Non renseignÃ©",
    ["BsmF_ReviewType"] = "Type",
    ["BsmF_ReviewNotSelected"] = "Non sÃ©lectionnÃ©",
    ["BsmF_ReviewNoReason"] = "Aucun motif sÃ©lectionnÃ©",
    ["BsmF_ReviewReturn"] = "Retour :",
    ["BsmF_ReviewNoDesig"] = "(Sans dÃ©signation)",
    ["BsmF_ReviewMore"] = "autres...",
    ["BsmF_ReviewNoCheckpoint"] = "Aucun checkpoint",
    ["BsmF_ReadyToSubmit"] = "PrÃªt Ã  soumettre",
    ["BsmF_FillForm"] = "ComplÃ©ter le formulaire",
    ["BsmF_NotFound"] = "Bon de sortie introuvable",
    ["BsmF_CannotEdit"] = "Ce bon ne peut plus Ãªtre modifiÃ©",
    ["BsmF_CurrentStatus"] = "Statut actuel :",
    ["BsmF_CreatedOn"] = "CrÃ©Ã© le :",
    ["BsmF_StatusLabel"] = "Statut :",
    ["BsmF_Requester"] = "Demandeur",
    ["BsmF_ExitReasonSection"] = "Motif de sortie",
    ["BsmF_MaterialDesc"] = "Description du matÃ©riel",
    ["BsmF_MaterialDescPlaceholder"] = "DÃ©crire le type...",
    ["BsmF_RouteSection"] = "ItinÃ©raire & Destination",
    ["BsmF_Description"] = "Description",
    ["BsmF_DescPlaceholder"] = "Description optionnelle...",
    ["BsmF_RecipientName"] = "Nom du destinataire",
    ["BsmF_RecipientAddress"] = "Adresse de destination",
    ["BsmF_VehicleSection"] = "VÃ©hicule & Chauffeur",
    ["BsmF_VehicleNumber"] = "NumÃ©ro de vÃ©hicule",
    ["BsmF_DriverName"] = "Nom du chauffeur",
    ["BsmF_DriverPhone"] = "TÃ©lÃ©phone du chauffeur",
    ["BsmF_ReturnDateSection"] = "Date de retour prÃ©vue",
    ["BsmF_ReturnDateLabel"] = "Date de retour",
    ["BsmF_ExpiryDateLabel"] = "Date d'expiration",
    ["BsmF_ExitReasonLabel"] = "Motif *",
    ["BsmF_ExitReasonPlaceholder"] = "DÃ©crire le motif de cette sortie...",
    ["BsmF_DesignationLabel"] = "DÃ©signation",
    ["BsmF_DesignationPlaceholder"] = "DÃ©signation...",
    ["BsmF_SerialLabel"] = "NÂ° de sÃ©rie / Code",
    ["BsmF_SerialPlaceholder"] = "NÂ° de sÃ©rie...",
    ["BsmF_AddMaterial"] = "Ajouter un matÃ©riel",

    // BSM View
    ["BsmV_PageTitle"] = "Bon de sortie",
    ["BsmV_PropertyRemoval"] = "Permis de sortie de propriÃ©tÃ©",
    ["BsmV_Loading"] = "Chargement du bon...",
    ["BsmV_NotFound"] = "Bon introuvable",
    ["BsmV_RequesterInfo"] = "Informations du demandeur",
    ["BsmV_Materials"] = "MatÃ©riels",
    ["BsmV_ColSerial"] = "Code / NÂ° de sÃ©rie",
    ["BsmV_ColDesc"] = "DÃ©signation",
    ["BsmV_Total"] = "Total",
    ["BsmV_ExitReason"] = "Motif de sortie",
    ["BsmV_AssocBem"] = "BEM associÃ©",
    ["BsmV_LoanReturn"] = "Retour de prÃªt",
    ["BsmV_PretTitle"] = "PrÃªt â€” Retour prÃ©vu :",
    ["BsmV_ReturnedOn"] = "RetournÃ© le",
    ["BsmV_Overdue"] = "En retard de",
    ["BsmV_Days"] = "jour(s)",

    // Vue gÃ©nÃ©rique
    ["View_Loading"] = "Chargement du bon...",
    ["View_AccessDenied"] = "AccÃ¨s refusÃ©",
    ["View_NotAllowed"] = "Vous n'Ãªtes pas autorisÃ© Ã  consulter ce bon.",
    ["View_NotFound"] = "Bon introuvable",
    ["View_DownloadPDF"] = "TÃ©lÃ©charger PDF",
    ["View_LoanReturn"] = "Retour de prÃªt",
    ["View_BEMHeader"] = "BON D'ENTRÃ‰E MATÃ‰RIEL",
    ["View_BSMHeader"] = "BON DE SORTIE MATÃ‰RIEL",
    ["View_PropertyEntry"] = "Permis d'entrÃ©e de propriÃ©tÃ©",
    ["View_PropertyRemoval"] = "Permis de sortie de propriÃ©tÃ©",
    ["View_ReturnedFor"] = "RetournÃ© pour modification â€”",
    ["View_RequesterInfo"] = "Informations du demandeur",
    ["View_LoanExpiry"] = "PrÃªt â€” Retour prÃ©vu :",
    ["View_ReturnedOn"] = "RetournÃ© le",
    ["View_Overdue"] = "En retard de",
    ["View_Days"] = "jour(s)",

    // PCountdown
    ["PCountdown_Returned"] = "RetournÃ©",
    ["PCountdown_Today"] = "Aujourd'hui",
    ["PCountdown_Tomorrow"] = "Demain",
    ["PCountdown_LoanClosed"] = "PrÃªt clÃ´turÃ©",
    ["PCountdown_OverdueBadge"] = "âš ï¸ EN RETARD",
    ["PCountdown_ReturnTodayBadge"] = "ðŸ”” RETOUR AUJOURD'HUI",
    ["PCountdown_SoonBadge"] = "â° BientÃ´t",
    ["PCountdown_Remaining"] = "Restant",
    ["PCountdown_OverdueLabel"] = "en retard",

    // WF Indicator
    ["WF_Title"] = "Flux d'approbation",
    ["WF_StepCreated"] = "CrÃ©ation",
    ["WF_StepIdentification"] = "Approbation Identification",

    // BEM searcher
    ["Bem_InvalidId"] = "Veuillez saisir un identifiant numÃ©rique valide",
    ["Bem_NotAvailable"] = "BEM introuvable ou non disponible",

    // Dmt
    ["Dmt_Placeholder"] = "DÃ©crire le type/objectif...",

    // Sdd
    ["Sdd_AnomalyBadge"] = "Anomalie",
    ["Sdd_RefDocument"] = "RÃ©fÃ©rence du document",
    ["Sdd_TypeDocument"] = "Type de document",
    ["Sdd_TypeMouvement"] = "Type de mouvement",
    ["Sdd_Barrier"] = "BarriÃ¨re",
    ["Sdd_Agent"] = "Agent de sÃ©curitÃ©",
    ["Sdd_ProofNumber"] = "NumÃ©ro de preuve",
    ["Sdd_PlannedRoute"] = "ITINÃ‰RAIRE PRÃ‰VU",
    ["Sdd_Origin"] = "Origine",
    ["Sdd_Destination"] = "Destination",
    ["Sdd_AnomalyReported"] = "Anomalie signalÃ©e",
    ["Sdd_Btn_Reprint"] = "RÃ©imprimer la preuve",
    ["Sdd_Btn_ViewBon"] = "Voir le document",
    ["Sdd_Btn_Close"] = "Fermer",

    // Ppd
    ["Ppd_Confirmed"] = "PASSAGE CONFIRMÃ‰",
    ["Ppd_ProofNumber"] = "NumÃ©ro de preuve",
    ["Ppd_DateTime"] = "Date & Heure",
    ["Ppd_Barrier"] = "BarriÃ¨re",
    ["Ppd_BonRef"] = "RÃ©fÃ©rence du document",
    ["Ppd_Agent"] = "Agent",
    ["Ppd_From"] = "Origine (DE)",
    ["Ppd_To"] = "Destination (VERS)",
    ["Ppd_Materials"] = "Nombre de matÃ©riels",
    ["Ppd_Observations"] = "Observations",
    ["Ppd_QrCode"] = "Code QR de vÃ©rification",
    ["Ppd_Btn_Print"] = "Imprimer",
    ["Ppd_Btn_Close"] = "Fermer",

    // Tad
    ["Tad_Document"] = "Document :",
    ["Tad_ResolutionLabel"] = "RÃ©solution",
    ["Tad_ResolutionPlaceholder"] = "DÃ©crire comment l'anomalie a Ã©tÃ© rÃ©solue...",
    ["Tad_CorrectiveLabel"] = "Actions correctives",
    ["Tad_CorrectivePlaceholder"] = "Actions prises pour Ã©viter la rÃ©currence (optionnel)...",
    ["Tad_Btn_Cancel"] = "Annuler",
    ["Tad_Btn_MarkResolved"] = "Marquer comme rÃ©solu",

    // Sad
    ["Sad_Title"] = "Signaler une anomalie",
    ["Sad_BonConcerne"] = "Document concernÃ©",
    ["Sad_TypeLabel"] = "Type d'anomalie *",
    ["Sad_TypePlaceholder"] = "SÃ©lectionner le type...",
    ["Sad_GravityLabel"] = "Niveau de sÃ©vÃ©ritÃ© *",
    ["Sad_DescLabel"] = "Description *",
    ["Sad_DescPlaceholder"] = "DÃ©crire l'anomalie observÃ©e...",
    ["Sad_Btn_Cancel"] = "Annuler",
    ["Sad_Btn_Report"] = "Signaler",

    // Rad
    ["Rad_Prompt"] = "Veuillez indiquer le motif de rÃ©ouverture de cette anomalie.",
    ["Rad_MotifLabel"] = "Motif",
    ["Rad_MotifPlaceholder"] = "Pourquoi rouvrir cette anomalie...",
    ["Rad_Btn_Cancel"] = "Annuler",
    ["Rad_Btn_Reopen"] = "Rouvrir",

    // Adb
    ["Adb_Title"] = "Tableau de bord des anomalies",
    ["Adb_LastUpdate"] = "Vue d'ensemble des anomalies - DerniÃ¨re mise Ã  jour :",
    ["Adb_Btn_ViewAll"] = "Voir tout",
    ["Adb_Card_Unresolved"] = "Non rÃ©solu",
    ["Adb_Card_Critical"] = "Critique",
    ["Adb_Card_Resolution"] = "Taux de rÃ©solution",
    ["Adb_Card_AvgDelay"] = "DÃ©lai moyen",
    ["Adb_Chart_ByType"] = "Distribution par type",
    ["Adb_Chart_ByGravity"] = "Distribution par sÃ©vÃ©ritÃ©",
    ["Adb_Chart_Count"] = "Nombre",
    ["Adb_NoData"] = "Aucune donnÃ©e disponible",
    ["Adb_Recent"] = "Anomalies rÃ©centes (24h)",
    ["Adb_NoRecent"] = "Aucune anomalie dans les derniÃ¨res 24h",
    ["Adb_Alert_CriticalPending"] = "Attention : anomalie(s) critique(s) en attente !",
    ["Adb_Alert_CriticalMsg"] = "Ces anomalies nÃ©cessitent une attention immÃ©diate de l'Ã©quipe Investigation.",
    ["Adb_Btn_Process"] = "Traiter",

    // Adl
    ["Adl_NotFound"] = "Anomalie introuvable",
    ["Adl_Btn_Back"] = "Retour Ã  la liste",
    ["Adl_Btn_Process"] = "Traiter",
    ["Adl_Btn_Reopen"] = "Rouvrir",
    ["Adl_GravityLabel"] = "NIVEAU DE SÃ‰VÃ‰RITÃ‰",
    ["Adl_StatusLabel"] = "STATUT",
    ["Adl_Statut_Traitee"] = "RÃ©solu",
    ["Adl_Statut_EnAttente"] = "En attente",
    ["Adl_Sec_Details"] = "DÃ©tails de l'anomalie",
    ["Adl_AnomalyType"] = "Type d'anomalie",
    ["Adl_DocConcerned"] = "Document concernÃ©",
    ["Adl_Barrier"] = "BarriÃ¨re",
    ["Adl_Description"] = "Description",
    ["Adl_Sec_AssocDoc"] = "Document associÃ©",
    ["Adl_BemLabel"] = "Document d'entrÃ©e",
    ["Adl_BsmLabel"] = "Document de sortie",
    ["Adl_DocTriggered"] = "Ce document a dÃ©clenchÃ© l'anomalie lors d'un contrÃ´le de sÃ©curitÃ©.",
    ["Adl_Btn_ViewFullDoc"] = "Voir le document complet",
    ["Adl_Sec_AssocScan"] = "Scan associÃ©",
    ["Adl_Scan_DateTime"] = "Date/Heure",
    ["Adl_Scan_Barrier"] = "BarriÃ¨re",
    ["Adl_Scan_Agent"] = "Agent",
    ["Adl_Scan_Status"] = "Statut du scan",
    ["Adl_Sec_Resolution"] = "RÃ©solution",
    ["Adl_CorrectiveActions"] = "Actions correctives",

    // BSL
    ["Bsl_PageTitle"] = "Bons de sortie - KCC Material Flow",
    ["Bsl_Title"] = "Bons de sortie",
    ["Bsl_Subtitle"] = "GÃ©rer les sorties de matÃ©riels",
    ["Bsl_New"] = "Nouveau bon de sortie",
    ["Bsl_ActiveFilter"] = "Filtre actif :",
    ["Bsl_FilterPending"] = "En attente",
    ["Bsl_FilterApproved"] = "ApprouvÃ©",
    ["Bsl_SearchPlaceholder"] = "Rechercher par rÃ©fÃ©rence, demandeur, destination...",
    ["Bsl_AllTypes"] = "Tous les types",
    ["Bsl_Loading"] = "Chargement des bons de sortie...",
    ["Bsl_Empty"] = "Aucun bon de sortie",
    ["Bsl_NoResults"] = "Aucun rÃ©sultat ne correspond aux critÃ¨res.",
    ["Bsl_ColType"] = "Type",
    ["Bsl_ColReference"] = "RÃ©fÃ©rence",
    ["Bsl_ColDestination"] = "Destination",
    ["Bsl_TypeExterne"] = "Externe",
    ["Bsl_TypeInterne"] = "Interne",
    ["Bsl_TypePret"] = "PrÃªt",
    ["Bsl_TypeSortie"] = "Sortie",

    // PExt
    ["PExt_Note"] = "Note : L'extension de la date de retour est rÃ©servÃ©e au dÃ©partement Identification.",
    ["PExt_CurrentDate"] = "Date de retour actuelle",
    ["PExt_NewDate"] = "Nouvelle date de retour *",
    ["PExt_NewDatePlaceholder"] = "SÃ©lectionner une date...",
    ["PExt_Reason"] = "Motif d'extension *",
    ["PExt_SelectReason"] = "SÃ©lectionner un motif...",
    ["PExt_OtherReason"] = "PrÃ©ciser le motif *",
    ["PExt_OtherPlaceholder"] = "Expliquer le motif...",
    ["PExt_Duration"] = "DurÃ©e d'extension :",
    ["PExt_Confirm"] = "Confirmer l'extension",
    ["PExt_ExtendFailed"] = "Impossible d'Ã©tendre",

    // PRet
    ["PRet_PageTitle"] = "Retour de prÃªt - KCC Material Flow",
    ["PRet_NotFound"] = "PrÃªt introuvable ou inaccessible.",
    ["PRet_AlreadyReturned"] = "Ce prÃªt a dÃ©jÃ  Ã©tÃ© retournÃ© le",
    ["PRet_Title"] = "Confirmation de retour",
    ["PRet_Subtitle"] = "CONFIRMATION DE RETOUR DE PRÃŠT",
    ["PRet_LoanInfo"] = "Informations du prÃªt",
    ["PRet_ExitDate"] = "Date de sortie",
    ["PRet_Materials"] = "MatÃ©riels Ã  retourner",
    ["PRet_RecordReturn"] = "Enregistrer le retour",
    ["PRet_EffectiveDate"] = "Date de retour effective *",
    ["PRet_ReceivedBy"] = "ReÃ§u par",
    ["PRet_AgentPlaceholder"] = "Nom de l'agent",
    ["PRet_MaterialState"] = "Ã‰tat gÃ©nÃ©ral du matÃ©riel *",
    ["PRet_StateGood"] = "Bon Ã©tat",
    ["PRet_StateWorn"] = "UsÃ©",
    ["PRet_StateDamaged"] = "EndommagÃ©",
    ["PRet_StateIncomplete"] = "Incomplet",
    ["PRet_DamageAlert"] = "Veuillez dÃ©crire les dommages ou articles manquants.",
    ["PRet_Observations"] = "Observations",
    ["PRet_ObsPlaceholder"] = "DÃ©crire l'Ã©tat du matÃ©riel...",
    ["PRet_Confirm"] = "Confirmer le retour",
    ["PRet_DescDamage"] = "DÃ©crire les dommages/articles manquants",

    // Rtl
    ["Rtl_Desc"] = "Enregistrer les informations de retour du prÃªt.",
    ["Rtl_StateLabel"] = "Ã‰tat du matÃ©riel au retour",
    ["Rtl_ObsPlaceholder"] = "Observations...",
    ["Rtl_Confirm"] = "Confirmer le retour",

    // Adif
    ["Adif_OldValue"] = "Ancienne valeur",
    ["Adif_NewValue"] = "Nouvelle valeur",
    ["Adif_Empty"] = "(vide)",
    ["Adif_Date"] = "Date",
    ["Adif_User"] = "Utilisateur",
    ["Adif_Action"] = "Action",
    ["Adif_Entity"] = "EntitÃ©",
    ["Adif_IP"] = "Adresse IP",

    // Imd
    ["Imd_Title"] = "Import des donnÃ©es de rÃ©fÃ©rence",
    ["Imd_Subtitle"] = "Charger DATA.xlsx â†’ staging (SociÃ©tÃ©s / Contrats) + mise Ã  jour directe des employÃ©s avec rÃ©solution ReportTo",
    ["Imd_Step1Title"] = "Ã‰tape 1 â€” Charger le fichier xlsx en staging",
    ["Imd_Step1Hint"] = "Le fichier doit contenir 3 feuilles : SociÃ©tÃ©, Contrat, Feuille3 (employÃ©s).",
    ["Imd_Reading"] = "Lecture en coursâ€¦",
    ["Imd_ImportSuccess"] = "Import staging rÃ©ussi",
    ["Imd_Step2Title"] = "Ã‰tape 2 â€” Importer les lots",
    ["Imd_NoBatch"] = "Aucun lot d'import en attente. Chargez un fichier ci-dessus.",
    ["Imd_ColBatch"] = "Lot (UTC)",
    ["Imd_ColCompanies"] = "SociÃ©tÃ©s",
    ["Imd_ColContracts"] = "Contrats",
    ["Imd_BtnMerge"] = "Fusionner",
    ["Imd_BtnPurge"] = "Purger",
    ["Imd_MergeSuccess"] = "Fusion terminÃ©e",
    ["Imd_Warnings"] = "avertissement(s)",

    // Imp (impersonation admin page)
    ["Imp_Subtitle"] = "Simuler la session d'un autre employÃ© pour voir ce qu'il voit. RÃ©servÃ© au vrai SuperAdmin.",
    ["Imp_ActiveSession"] = "Session active :",
    ["Imp_LoggedAs"] = "vous Ãªtes connectÃ© en tant que",
    ["Imp_RealAccount"] = "compte rÃ©el",
    ["Imp_BtnStop"] = "ArrÃªter",
    ["Imp_SearchTitle"] = "Rechercher un employÃ©",
    ["Imp_SearchPh"] = "Code employÃ©, nom ou dÃ©partementâ€¦ (min. 2 caractÃ¨res)",
    ["Imp_TypeMin2"] = "Saisissez au moins 2 caractÃ¨res pour rechercher.",
    ["Imp_NoEmployee"] = "Aucun employÃ© trouvÃ© pour",
    ["Imp_Results"] = "rÃ©sultat(s)",
    ["Imp_EmptyGrid"] = "Aucun employÃ©.",
    ["Imp_ColMatricule"] = "Matricule",
    ["Imp_ColName"] = "Nom",
    ["Imp_ColDept"] = "DÃ©partement",
    ["Imp_ColLogin"] = "Login Windows",
    ["Imp_BtnBecome"] = "Devenir",

    // Wed
    ["Wed_GenericWorkflow"] = "Ce workflow s'applique Ã  tous les dÃ©partements sans configuration spÃ©cifique.",
    ["Wed_StepsTitle"] = "Ã‰tapes d'approbation",
    ["Wed_Btn_AddStep"] = "Ajouter une Ã©tape",
    ["Wed_AutoTooltip"] = "Approbateur rÃ©solu automatiquement depuis la hiÃ©rarchie",
    ["Wed_ChainPreview"] = "AperÃ§u de la chaÃ®ne :",

    // Columns
    ["Col_Company"] = "SociÃ©tÃ©",
    ["Col_Requester"] = "Demandeur",
    ["Col_Status"] = "Statut",
    ["Col_Materials"] = "MatÃ©riels",
    ["Col_Quantity"] = "QtÃ©",
    ["Col_Designation"] = "DÃ©signation",
    ["Col_Category"] = "CatÃ©gorie",
    ["Col_Department"] = "DÃ©partement",
    ["Col_Level"] = "Niveau",
    ["Col_Name"] = "Nom",
    ["Col_Key"] = "ClÃ©",
    ["Col_Value"] = "Valeur",
    ["Col_User"] = "Utilisateur",
    ["Col_Approver"] = "Approbateur",
    ["Col_Reason"] = "Motif",

    // Divers
    ["BsPrint_AccessMsg"] = "Seul le dernier approbateur (Identification) peut imprimer ce bon.",
};

// Load the resx as XML
var doc = XDocument.Load(file);
int count = 0;

foreach (var dataEl in doc.Descendants("data"))
{
    var nameAttr = dataEl.Attribute("name")?.Value;
    if (nameAttr != null && translations.TryGetValue(nameAttr, out var french))
    {
        var valueEl = dataEl.Element("value");
        if (valueEl != null && valueEl.Value != french)
        {
            Console.WriteLine($"  {nameAttr}: \"{valueEl.Value}\" -> \"{french}\"");
            valueEl.Value = french;
            count++;
        }
    }
}

Console.WriteLine($"\nTotal replaced: {count}");
doc.Save(file);
Console.WriteLine("File saved.");

